// Code generated by scripts/gen-codecs; DO NOT EDIT.

package oboron

// DgcmsivC32 is the fixed-format codec for "dgcmsiv.c32". The encoding is part of the
// type name and never optional.
type DgcmsivC32 struct{ ob *Ob }

// NewDgcmsivC32 creates a DgcmsivC32 from a key string.
func NewDgcmsivC32(key string) (*DgcmsivC32, error) {
	ob, err := New("dgcmsiv.c32", key)
	if err != nil {
		return nil, err
	}
	return &DgcmsivC32{ob}, nil
}

// NewDgcmsivC32FromBytes creates a DgcmsivC32 from a raw key byte slice.
func NewDgcmsivC32FromBytes(key []byte) (*DgcmsivC32, error) {
	ob, err := NewObFromBytes("dgcmsiv.c32", key)
	if err != nil {
		return nil, err
	}
	return &DgcmsivC32{ob}, nil
}

// NewDgcmsivC32Keyless creates a DgcmsivC32 with the hardcoded key (testing only — NOT SECURE).
func NewDgcmsivC32Keyless() (*DgcmsivC32, error) {
	ob, err := NewObKeyless("dgcmsiv.c32")
	if err != nil {
		return nil, err
	}
	return &DgcmsivC32{ob}, nil
}

// Enc encrypts and encodes plaintext to obtext.
func (c *DgcmsivC32) Enc(plaintext string) (string, error) { return c.ob.Enc(plaintext) }

// Dec decodes and decrypts obtext to plaintext.
func (c *DgcmsivC32) Dec(obtext string) (string, error) { return c.ob.Dec(obtext) }

// Format returns the fixed format (scheme + encoding).
func (c *DgcmsivC32) Format() Format { return c.ob.Format() }

// Scheme returns the fixed scheme.
func (c *DgcmsivC32) Scheme() Scheme { return c.ob.Scheme() }

// Encoding returns the fixed encoding.
func (c *DgcmsivC32) Encoding() Encoding { return c.ob.Encoding() }

var _ Codec = (*DgcmsivC32)(nil)

// DgcmsivB32 is the fixed-format codec for "dgcmsiv.b32". The encoding is part of the
// type name and never optional.
type DgcmsivB32 struct{ ob *Ob }

// NewDgcmsivB32 creates a DgcmsivB32 from a key string.
func NewDgcmsivB32(key string) (*DgcmsivB32, error) {
	ob, err := New("dgcmsiv.b32", key)
	if err != nil {
		return nil, err
	}
	return &DgcmsivB32{ob}, nil
}

// NewDgcmsivB32FromBytes creates a DgcmsivB32 from a raw key byte slice.
func NewDgcmsivB32FromBytes(key []byte) (*DgcmsivB32, error) {
	ob, err := NewObFromBytes("dgcmsiv.b32", key)
	if err != nil {
		return nil, err
	}
	return &DgcmsivB32{ob}, nil
}

// NewDgcmsivB32Keyless creates a DgcmsivB32 with the hardcoded key (testing only — NOT SECURE).
func NewDgcmsivB32Keyless() (*DgcmsivB32, error) {
	ob, err := NewObKeyless("dgcmsiv.b32")
	if err != nil {
		return nil, err
	}
	return &DgcmsivB32{ob}, nil
}

// Enc encrypts and encodes plaintext to obtext.
func (c *DgcmsivB32) Enc(plaintext string) (string, error) { return c.ob.Enc(plaintext) }

// Dec decodes and decrypts obtext to plaintext.
func (c *DgcmsivB32) Dec(obtext string) (string, error) { return c.ob.Dec(obtext) }

// Format returns the fixed format (scheme + encoding).
func (c *DgcmsivB32) Format() Format { return c.ob.Format() }

// Scheme returns the fixed scheme.
func (c *DgcmsivB32) Scheme() Scheme { return c.ob.Scheme() }

// Encoding returns the fixed encoding.
func (c *DgcmsivB32) Encoding() Encoding { return c.ob.Encoding() }

var _ Codec = (*DgcmsivB32)(nil)

// DgcmsivB64 is the fixed-format codec for "dgcmsiv.b64". The encoding is part of the
// type name and never optional.
type DgcmsivB64 struct{ ob *Ob }

// NewDgcmsivB64 creates a DgcmsivB64 from a key string.
func NewDgcmsivB64(key string) (*DgcmsivB64, error) {
	ob, err := New("dgcmsiv.b64", key)
	if err != nil {
		return nil, err
	}
	return &DgcmsivB64{ob}, nil
}

// NewDgcmsivB64FromBytes creates a DgcmsivB64 from a raw key byte slice.
func NewDgcmsivB64FromBytes(key []byte) (*DgcmsivB64, error) {
	ob, err := NewObFromBytes("dgcmsiv.b64", key)
	if err != nil {
		return nil, err
	}
	return &DgcmsivB64{ob}, nil
}

// NewDgcmsivB64Keyless creates a DgcmsivB64 with the hardcoded key (testing only — NOT SECURE).
func NewDgcmsivB64Keyless() (*DgcmsivB64, error) {
	ob, err := NewObKeyless("dgcmsiv.b64")
	if err != nil {
		return nil, err
	}
	return &DgcmsivB64{ob}, nil
}

// Enc encrypts and encodes plaintext to obtext.
func (c *DgcmsivB64) Enc(plaintext string) (string, error) { return c.ob.Enc(plaintext) }

// Dec decodes and decrypts obtext to plaintext.
func (c *DgcmsivB64) Dec(obtext string) (string, error) { return c.ob.Dec(obtext) }

// Format returns the fixed format (scheme + encoding).
func (c *DgcmsivB64) Format() Format { return c.ob.Format() }

// Scheme returns the fixed scheme.
func (c *DgcmsivB64) Scheme() Scheme { return c.ob.Scheme() }

// Encoding returns the fixed encoding.
func (c *DgcmsivB64) Encoding() Encoding { return c.ob.Encoding() }

var _ Codec = (*DgcmsivB64)(nil)

// DgcmsivHex is the fixed-format codec for "dgcmsiv.hex". The encoding is part of the
// type name and never optional.
type DgcmsivHex struct{ ob *Ob }

// NewDgcmsivHex creates a DgcmsivHex from a key string.
func NewDgcmsivHex(key string) (*DgcmsivHex, error) {
	ob, err := New("dgcmsiv.hex", key)
	if err != nil {
		return nil, err
	}
	return &DgcmsivHex{ob}, nil
}

// NewDgcmsivHexFromBytes creates a DgcmsivHex from a raw key byte slice.
func NewDgcmsivHexFromBytes(key []byte) (*DgcmsivHex, error) {
	ob, err := NewObFromBytes("dgcmsiv.hex", key)
	if err != nil {
		return nil, err
	}
	return &DgcmsivHex{ob}, nil
}

// NewDgcmsivHexKeyless creates a DgcmsivHex with the hardcoded key (testing only — NOT SECURE).
func NewDgcmsivHexKeyless() (*DgcmsivHex, error) {
	ob, err := NewObKeyless("dgcmsiv.hex")
	if err != nil {
		return nil, err
	}
	return &DgcmsivHex{ob}, nil
}

// Enc encrypts and encodes plaintext to obtext.
func (c *DgcmsivHex) Enc(plaintext string) (string, error) { return c.ob.Enc(plaintext) }

// Dec decodes and decrypts obtext to plaintext.
func (c *DgcmsivHex) Dec(obtext string) (string, error) { return c.ob.Dec(obtext) }

// Format returns the fixed format (scheme + encoding).
func (c *DgcmsivHex) Format() Format { return c.ob.Format() }

// Scheme returns the fixed scheme.
func (c *DgcmsivHex) Scheme() Scheme { return c.ob.Scheme() }

// Encoding returns the fixed encoding.
func (c *DgcmsivHex) Encoding() Encoding { return c.ob.Encoding() }

var _ Codec = (*DgcmsivHex)(nil)

// DsivC32 is the fixed-format codec for "dsiv.c32". The encoding is part of the
// type name and never optional.
type DsivC32 struct{ ob *Ob }

// NewDsivC32 creates a DsivC32 from a key string.
func NewDsivC32(key string) (*DsivC32, error) {
	ob, err := New("dsiv.c32", key)
	if err != nil {
		return nil, err
	}
	return &DsivC32{ob}, nil
}

// NewDsivC32FromBytes creates a DsivC32 from a raw key byte slice.
func NewDsivC32FromBytes(key []byte) (*DsivC32, error) {
	ob, err := NewObFromBytes("dsiv.c32", key)
	if err != nil {
		return nil, err
	}
	return &DsivC32{ob}, nil
}

// NewDsivC32Keyless creates a DsivC32 with the hardcoded key (testing only — NOT SECURE).
func NewDsivC32Keyless() (*DsivC32, error) {
	ob, err := NewObKeyless("dsiv.c32")
	if err != nil {
		return nil, err
	}
	return &DsivC32{ob}, nil
}

// Enc encrypts and encodes plaintext to obtext.
func (c *DsivC32) Enc(plaintext string) (string, error) { return c.ob.Enc(plaintext) }

// Dec decodes and decrypts obtext to plaintext.
func (c *DsivC32) Dec(obtext string) (string, error) { return c.ob.Dec(obtext) }

// Format returns the fixed format (scheme + encoding).
func (c *DsivC32) Format() Format { return c.ob.Format() }

// Scheme returns the fixed scheme.
func (c *DsivC32) Scheme() Scheme { return c.ob.Scheme() }

// Encoding returns the fixed encoding.
func (c *DsivC32) Encoding() Encoding { return c.ob.Encoding() }

var _ Codec = (*DsivC32)(nil)

// DsivB32 is the fixed-format codec for "dsiv.b32". The encoding is part of the
// type name and never optional.
type DsivB32 struct{ ob *Ob }

// NewDsivB32 creates a DsivB32 from a key string.
func NewDsivB32(key string) (*DsivB32, error) {
	ob, err := New("dsiv.b32", key)
	if err != nil {
		return nil, err
	}
	return &DsivB32{ob}, nil
}

// NewDsivB32FromBytes creates a DsivB32 from a raw key byte slice.
func NewDsivB32FromBytes(key []byte) (*DsivB32, error) {
	ob, err := NewObFromBytes("dsiv.b32", key)
	if err != nil {
		return nil, err
	}
	return &DsivB32{ob}, nil
}

// NewDsivB32Keyless creates a DsivB32 with the hardcoded key (testing only — NOT SECURE).
func NewDsivB32Keyless() (*DsivB32, error) {
	ob, err := NewObKeyless("dsiv.b32")
	if err != nil {
		return nil, err
	}
	return &DsivB32{ob}, nil
}

// Enc encrypts and encodes plaintext to obtext.
func (c *DsivB32) Enc(plaintext string) (string, error) { return c.ob.Enc(plaintext) }

// Dec decodes and decrypts obtext to plaintext.
func (c *DsivB32) Dec(obtext string) (string, error) { return c.ob.Dec(obtext) }

// Format returns the fixed format (scheme + encoding).
func (c *DsivB32) Format() Format { return c.ob.Format() }

// Scheme returns the fixed scheme.
func (c *DsivB32) Scheme() Scheme { return c.ob.Scheme() }

// Encoding returns the fixed encoding.
func (c *DsivB32) Encoding() Encoding { return c.ob.Encoding() }

var _ Codec = (*DsivB32)(nil)

// DsivB64 is the fixed-format codec for "dsiv.b64". The encoding is part of the
// type name and never optional.
type DsivB64 struct{ ob *Ob }

// NewDsivB64 creates a DsivB64 from a key string.
func NewDsivB64(key string) (*DsivB64, error) {
	ob, err := New("dsiv.b64", key)
	if err != nil {
		return nil, err
	}
	return &DsivB64{ob}, nil
}

// NewDsivB64FromBytes creates a DsivB64 from a raw key byte slice.
func NewDsivB64FromBytes(key []byte) (*DsivB64, error) {
	ob, err := NewObFromBytes("dsiv.b64", key)
	if err != nil {
		return nil, err
	}
	return &DsivB64{ob}, nil
}

// NewDsivB64Keyless creates a DsivB64 with the hardcoded key (testing only — NOT SECURE).
func NewDsivB64Keyless() (*DsivB64, error) {
	ob, err := NewObKeyless("dsiv.b64")
	if err != nil {
		return nil, err
	}
	return &DsivB64{ob}, nil
}

// Enc encrypts and encodes plaintext to obtext.
func (c *DsivB64) Enc(plaintext string) (string, error) { return c.ob.Enc(plaintext) }

// Dec decodes and decrypts obtext to plaintext.
func (c *DsivB64) Dec(obtext string) (string, error) { return c.ob.Dec(obtext) }

// Format returns the fixed format (scheme + encoding).
func (c *DsivB64) Format() Format { return c.ob.Format() }

// Scheme returns the fixed scheme.
func (c *DsivB64) Scheme() Scheme { return c.ob.Scheme() }

// Encoding returns the fixed encoding.
func (c *DsivB64) Encoding() Encoding { return c.ob.Encoding() }

var _ Codec = (*DsivB64)(nil)

// DsivHex is the fixed-format codec for "dsiv.hex". The encoding is part of the
// type name and never optional.
type DsivHex struct{ ob *Ob }

// NewDsivHex creates a DsivHex from a key string.
func NewDsivHex(key string) (*DsivHex, error) {
	ob, err := New("dsiv.hex", key)
	if err != nil {
		return nil, err
	}
	return &DsivHex{ob}, nil
}

// NewDsivHexFromBytes creates a DsivHex from a raw key byte slice.
func NewDsivHexFromBytes(key []byte) (*DsivHex, error) {
	ob, err := NewObFromBytes("dsiv.hex", key)
	if err != nil {
		return nil, err
	}
	return &DsivHex{ob}, nil
}

// NewDsivHexKeyless creates a DsivHex with the hardcoded key (testing only — NOT SECURE).
func NewDsivHexKeyless() (*DsivHex, error) {
	ob, err := NewObKeyless("dsiv.hex")
	if err != nil {
		return nil, err
	}
	return &DsivHex{ob}, nil
}

// Enc encrypts and encodes plaintext to obtext.
func (c *DsivHex) Enc(plaintext string) (string, error) { return c.ob.Enc(plaintext) }

// Dec decodes and decrypts obtext to plaintext.
func (c *DsivHex) Dec(obtext string) (string, error) { return c.ob.Dec(obtext) }

// Format returns the fixed format (scheme + encoding).
func (c *DsivHex) Format() Format { return c.ob.Format() }

// Scheme returns the fixed scheme.
func (c *DsivHex) Scheme() Scheme { return c.ob.Scheme() }

// Encoding returns the fixed encoding.
func (c *DsivHex) Encoding() Encoding { return c.ob.Encoding() }

var _ Codec = (*DsivHex)(nil)

// PgcmsivC32 is the fixed-format codec for "pgcmsiv.c32". The encoding is part of the
// type name and never optional.
type PgcmsivC32 struct{ ob *Ob }

// NewPgcmsivC32 creates a PgcmsivC32 from a key string.
func NewPgcmsivC32(key string) (*PgcmsivC32, error) {
	ob, err := New("pgcmsiv.c32", key)
	if err != nil {
		return nil, err
	}
	return &PgcmsivC32{ob}, nil
}

// NewPgcmsivC32FromBytes creates a PgcmsivC32 from a raw key byte slice.
func NewPgcmsivC32FromBytes(key []byte) (*PgcmsivC32, error) {
	ob, err := NewObFromBytes("pgcmsiv.c32", key)
	if err != nil {
		return nil, err
	}
	return &PgcmsivC32{ob}, nil
}

// NewPgcmsivC32Keyless creates a PgcmsivC32 with the hardcoded key (testing only — NOT SECURE).
func NewPgcmsivC32Keyless() (*PgcmsivC32, error) {
	ob, err := NewObKeyless("pgcmsiv.c32")
	if err != nil {
		return nil, err
	}
	return &PgcmsivC32{ob}, nil
}

// Enc encrypts and encodes plaintext to obtext.
func (c *PgcmsivC32) Enc(plaintext string) (string, error) { return c.ob.Enc(plaintext) }

// Dec decodes and decrypts obtext to plaintext.
func (c *PgcmsivC32) Dec(obtext string) (string, error) { return c.ob.Dec(obtext) }

// Format returns the fixed format (scheme + encoding).
func (c *PgcmsivC32) Format() Format { return c.ob.Format() }

// Scheme returns the fixed scheme.
func (c *PgcmsivC32) Scheme() Scheme { return c.ob.Scheme() }

// Encoding returns the fixed encoding.
func (c *PgcmsivC32) Encoding() Encoding { return c.ob.Encoding() }

var _ Codec = (*PgcmsivC32)(nil)

// PgcmsivB32 is the fixed-format codec for "pgcmsiv.b32". The encoding is part of the
// type name and never optional.
type PgcmsivB32 struct{ ob *Ob }

// NewPgcmsivB32 creates a PgcmsivB32 from a key string.
func NewPgcmsivB32(key string) (*PgcmsivB32, error) {
	ob, err := New("pgcmsiv.b32", key)
	if err != nil {
		return nil, err
	}
	return &PgcmsivB32{ob}, nil
}

// NewPgcmsivB32FromBytes creates a PgcmsivB32 from a raw key byte slice.
func NewPgcmsivB32FromBytes(key []byte) (*PgcmsivB32, error) {
	ob, err := NewObFromBytes("pgcmsiv.b32", key)
	if err != nil {
		return nil, err
	}
	return &PgcmsivB32{ob}, nil
}

// NewPgcmsivB32Keyless creates a PgcmsivB32 with the hardcoded key (testing only — NOT SECURE).
func NewPgcmsivB32Keyless() (*PgcmsivB32, error) {
	ob, err := NewObKeyless("pgcmsiv.b32")
	if err != nil {
		return nil, err
	}
	return &PgcmsivB32{ob}, nil
}

// Enc encrypts and encodes plaintext to obtext.
func (c *PgcmsivB32) Enc(plaintext string) (string, error) { return c.ob.Enc(plaintext) }

// Dec decodes and decrypts obtext to plaintext.
func (c *PgcmsivB32) Dec(obtext string) (string, error) { return c.ob.Dec(obtext) }

// Format returns the fixed format (scheme + encoding).
func (c *PgcmsivB32) Format() Format { return c.ob.Format() }

// Scheme returns the fixed scheme.
func (c *PgcmsivB32) Scheme() Scheme { return c.ob.Scheme() }

// Encoding returns the fixed encoding.
func (c *PgcmsivB32) Encoding() Encoding { return c.ob.Encoding() }

var _ Codec = (*PgcmsivB32)(nil)

// PgcmsivB64 is the fixed-format codec for "pgcmsiv.b64". The encoding is part of the
// type name and never optional.
type PgcmsivB64 struct{ ob *Ob }

// NewPgcmsivB64 creates a PgcmsivB64 from a key string.
func NewPgcmsivB64(key string) (*PgcmsivB64, error) {
	ob, err := New("pgcmsiv.b64", key)
	if err != nil {
		return nil, err
	}
	return &PgcmsivB64{ob}, nil
}

// NewPgcmsivB64FromBytes creates a PgcmsivB64 from a raw key byte slice.
func NewPgcmsivB64FromBytes(key []byte) (*PgcmsivB64, error) {
	ob, err := NewObFromBytes("pgcmsiv.b64", key)
	if err != nil {
		return nil, err
	}
	return &PgcmsivB64{ob}, nil
}

// NewPgcmsivB64Keyless creates a PgcmsivB64 with the hardcoded key (testing only — NOT SECURE).
func NewPgcmsivB64Keyless() (*PgcmsivB64, error) {
	ob, err := NewObKeyless("pgcmsiv.b64")
	if err != nil {
		return nil, err
	}
	return &PgcmsivB64{ob}, nil
}

// Enc encrypts and encodes plaintext to obtext.
func (c *PgcmsivB64) Enc(plaintext string) (string, error) { return c.ob.Enc(plaintext) }

// Dec decodes and decrypts obtext to plaintext.
func (c *PgcmsivB64) Dec(obtext string) (string, error) { return c.ob.Dec(obtext) }

// Format returns the fixed format (scheme + encoding).
func (c *PgcmsivB64) Format() Format { return c.ob.Format() }

// Scheme returns the fixed scheme.
func (c *PgcmsivB64) Scheme() Scheme { return c.ob.Scheme() }

// Encoding returns the fixed encoding.
func (c *PgcmsivB64) Encoding() Encoding { return c.ob.Encoding() }

var _ Codec = (*PgcmsivB64)(nil)

// PgcmsivHex is the fixed-format codec for "pgcmsiv.hex". The encoding is part of the
// type name and never optional.
type PgcmsivHex struct{ ob *Ob }

// NewPgcmsivHex creates a PgcmsivHex from a key string.
func NewPgcmsivHex(key string) (*PgcmsivHex, error) {
	ob, err := New("pgcmsiv.hex", key)
	if err != nil {
		return nil, err
	}
	return &PgcmsivHex{ob}, nil
}

// NewPgcmsivHexFromBytes creates a PgcmsivHex from a raw key byte slice.
func NewPgcmsivHexFromBytes(key []byte) (*PgcmsivHex, error) {
	ob, err := NewObFromBytes("pgcmsiv.hex", key)
	if err != nil {
		return nil, err
	}
	return &PgcmsivHex{ob}, nil
}

// NewPgcmsivHexKeyless creates a PgcmsivHex with the hardcoded key (testing only — NOT SECURE).
func NewPgcmsivHexKeyless() (*PgcmsivHex, error) {
	ob, err := NewObKeyless("pgcmsiv.hex")
	if err != nil {
		return nil, err
	}
	return &PgcmsivHex{ob}, nil
}

// Enc encrypts and encodes plaintext to obtext.
func (c *PgcmsivHex) Enc(plaintext string) (string, error) { return c.ob.Enc(plaintext) }

// Dec decodes and decrypts obtext to plaintext.
func (c *PgcmsivHex) Dec(obtext string) (string, error) { return c.ob.Dec(obtext) }

// Format returns the fixed format (scheme + encoding).
func (c *PgcmsivHex) Format() Format { return c.ob.Format() }

// Scheme returns the fixed scheme.
func (c *PgcmsivHex) Scheme() Scheme { return c.ob.Scheme() }

// Encoding returns the fixed encoding.
func (c *PgcmsivHex) Encoding() Encoding { return c.ob.Encoding() }

var _ Codec = (*PgcmsivHex)(nil)

// PsivC32 is the fixed-format codec for "psiv.c32". The encoding is part of the
// type name and never optional.
type PsivC32 struct{ ob *Ob }

// NewPsivC32 creates a PsivC32 from a key string.
func NewPsivC32(key string) (*PsivC32, error) {
	ob, err := New("psiv.c32", key)
	if err != nil {
		return nil, err
	}
	return &PsivC32{ob}, nil
}

// NewPsivC32FromBytes creates a PsivC32 from a raw key byte slice.
func NewPsivC32FromBytes(key []byte) (*PsivC32, error) {
	ob, err := NewObFromBytes("psiv.c32", key)
	if err != nil {
		return nil, err
	}
	return &PsivC32{ob}, nil
}

// NewPsivC32Keyless creates a PsivC32 with the hardcoded key (testing only — NOT SECURE).
func NewPsivC32Keyless() (*PsivC32, error) {
	ob, err := NewObKeyless("psiv.c32")
	if err != nil {
		return nil, err
	}
	return &PsivC32{ob}, nil
}

// Enc encrypts and encodes plaintext to obtext.
func (c *PsivC32) Enc(plaintext string) (string, error) { return c.ob.Enc(plaintext) }

// Dec decodes and decrypts obtext to plaintext.
func (c *PsivC32) Dec(obtext string) (string, error) { return c.ob.Dec(obtext) }

// Format returns the fixed format (scheme + encoding).
func (c *PsivC32) Format() Format { return c.ob.Format() }

// Scheme returns the fixed scheme.
func (c *PsivC32) Scheme() Scheme { return c.ob.Scheme() }

// Encoding returns the fixed encoding.
func (c *PsivC32) Encoding() Encoding { return c.ob.Encoding() }

var _ Codec = (*PsivC32)(nil)

// PsivB32 is the fixed-format codec for "psiv.b32". The encoding is part of the
// type name and never optional.
type PsivB32 struct{ ob *Ob }

// NewPsivB32 creates a PsivB32 from a key string.
func NewPsivB32(key string) (*PsivB32, error) {
	ob, err := New("psiv.b32", key)
	if err != nil {
		return nil, err
	}
	return &PsivB32{ob}, nil
}

// NewPsivB32FromBytes creates a PsivB32 from a raw key byte slice.
func NewPsivB32FromBytes(key []byte) (*PsivB32, error) {
	ob, err := NewObFromBytes("psiv.b32", key)
	if err != nil {
		return nil, err
	}
	return &PsivB32{ob}, nil
}

// NewPsivB32Keyless creates a PsivB32 with the hardcoded key (testing only — NOT SECURE).
func NewPsivB32Keyless() (*PsivB32, error) {
	ob, err := NewObKeyless("psiv.b32")
	if err != nil {
		return nil, err
	}
	return &PsivB32{ob}, nil
}

// Enc encrypts and encodes plaintext to obtext.
func (c *PsivB32) Enc(plaintext string) (string, error) { return c.ob.Enc(plaintext) }

// Dec decodes and decrypts obtext to plaintext.
func (c *PsivB32) Dec(obtext string) (string, error) { return c.ob.Dec(obtext) }

// Format returns the fixed format (scheme + encoding).
func (c *PsivB32) Format() Format { return c.ob.Format() }

// Scheme returns the fixed scheme.
func (c *PsivB32) Scheme() Scheme { return c.ob.Scheme() }

// Encoding returns the fixed encoding.
func (c *PsivB32) Encoding() Encoding { return c.ob.Encoding() }

var _ Codec = (*PsivB32)(nil)

// PsivB64 is the fixed-format codec for "psiv.b64". The encoding is part of the
// type name and never optional.
type PsivB64 struct{ ob *Ob }

// NewPsivB64 creates a PsivB64 from a key string.
func NewPsivB64(key string) (*PsivB64, error) {
	ob, err := New("psiv.b64", key)
	if err != nil {
		return nil, err
	}
	return &PsivB64{ob}, nil
}

// NewPsivB64FromBytes creates a PsivB64 from a raw key byte slice.
func NewPsivB64FromBytes(key []byte) (*PsivB64, error) {
	ob, err := NewObFromBytes("psiv.b64", key)
	if err != nil {
		return nil, err
	}
	return &PsivB64{ob}, nil
}

// NewPsivB64Keyless creates a PsivB64 with the hardcoded key (testing only — NOT SECURE).
func NewPsivB64Keyless() (*PsivB64, error) {
	ob, err := NewObKeyless("psiv.b64")
	if err != nil {
		return nil, err
	}
	return &PsivB64{ob}, nil
}

// Enc encrypts and encodes plaintext to obtext.
func (c *PsivB64) Enc(plaintext string) (string, error) { return c.ob.Enc(plaintext) }

// Dec decodes and decrypts obtext to plaintext.
func (c *PsivB64) Dec(obtext string) (string, error) { return c.ob.Dec(obtext) }

// Format returns the fixed format (scheme + encoding).
func (c *PsivB64) Format() Format { return c.ob.Format() }

// Scheme returns the fixed scheme.
func (c *PsivB64) Scheme() Scheme { return c.ob.Scheme() }

// Encoding returns the fixed encoding.
func (c *PsivB64) Encoding() Encoding { return c.ob.Encoding() }

var _ Codec = (*PsivB64)(nil)

// PsivHex is the fixed-format codec for "psiv.hex". The encoding is part of the
// type name and never optional.
type PsivHex struct{ ob *Ob }

// NewPsivHex creates a PsivHex from a key string.
func NewPsivHex(key string) (*PsivHex, error) {
	ob, err := New("psiv.hex", key)
	if err != nil {
		return nil, err
	}
	return &PsivHex{ob}, nil
}

// NewPsivHexFromBytes creates a PsivHex from a raw key byte slice.
func NewPsivHexFromBytes(key []byte) (*PsivHex, error) {
	ob, err := NewObFromBytes("psiv.hex", key)
	if err != nil {
		return nil, err
	}
	return &PsivHex{ob}, nil
}

// NewPsivHexKeyless creates a PsivHex with the hardcoded key (testing only — NOT SECURE).
func NewPsivHexKeyless() (*PsivHex, error) {
	ob, err := NewObKeyless("psiv.hex")
	if err != nil {
		return nil, err
	}
	return &PsivHex{ob}, nil
}

// Enc encrypts and encodes plaintext to obtext.
func (c *PsivHex) Enc(plaintext string) (string, error) { return c.ob.Enc(plaintext) }

// Dec decodes and decrypts obtext to plaintext.
func (c *PsivHex) Dec(obtext string) (string, error) { return c.ob.Dec(obtext) }

// Format returns the fixed format (scheme + encoding).
func (c *PsivHex) Format() Format { return c.ob.Format() }

// Scheme returns the fixed scheme.
func (c *PsivHex) Scheme() Scheme { return c.ob.Scheme() }

// Encoding returns the fixed encoding.
func (c *PsivHex) Encoding() Encoding { return c.ob.Encoding() }

var _ Codec = (*PsivHex)(nil)
