// Code generated by scripts/gen-codecs; DO NOT EDIT.

package oboron

// AagsC32 is the fixed-format codec for "aags.c32". The encoding is part of the
// type name and never optional.
type AagsC32 struct{ ob *Ob }

// NewAagsC32 creates a AagsC32 from a key string.
func NewAagsC32(key string) (*AagsC32, error) {
	ob, err := New("aags.c32", key)
	if err != nil {
		return nil, err
	}
	return &AagsC32{ob}, nil
}

// NewAagsC32FromBytes creates a AagsC32 from a raw key byte slice.
func NewAagsC32FromBytes(key []byte) (*AagsC32, error) {
	ob, err := NewObFromBytes("aags.c32", key)
	if err != nil {
		return nil, err
	}
	return &AagsC32{ob}, nil
}

// NewAagsC32Keyless creates a AagsC32 with the hardcoded key (testing only — NOT SECURE).
func NewAagsC32Keyless() (*AagsC32, error) {
	ob, err := NewObKeyless("aags.c32")
	if err != nil {
		return nil, err
	}
	return &AagsC32{ob}, nil
}

// Enc encrypts and encodes plaintext to obtext.
func (c *AagsC32) Enc(plaintext string) (string, error) { return c.ob.Enc(plaintext) }

// Dec decodes and decrypts obtext to plaintext.
func (c *AagsC32) Dec(obtext string) (string, error) { return c.ob.Dec(obtext) }

// Format returns the fixed format (scheme + encoding).
func (c *AagsC32) Format() Format { return c.ob.Format() }

// Scheme returns the fixed scheme.
func (c *AagsC32) Scheme() Scheme { return c.ob.Scheme() }

// Encoding returns the fixed encoding.
func (c *AagsC32) Encoding() Encoding { return c.ob.Encoding() }

var _ Codec = (*AagsC32)(nil)

// AagsB32 is the fixed-format codec for "aags.b32". The encoding is part of the
// type name and never optional.
type AagsB32 struct{ ob *Ob }

// NewAagsB32 creates a AagsB32 from a key string.
func NewAagsB32(key string) (*AagsB32, error) {
	ob, err := New("aags.b32", key)
	if err != nil {
		return nil, err
	}
	return &AagsB32{ob}, nil
}

// NewAagsB32FromBytes creates a AagsB32 from a raw key byte slice.
func NewAagsB32FromBytes(key []byte) (*AagsB32, error) {
	ob, err := NewObFromBytes("aags.b32", key)
	if err != nil {
		return nil, err
	}
	return &AagsB32{ob}, nil
}

// NewAagsB32Keyless creates a AagsB32 with the hardcoded key (testing only — NOT SECURE).
func NewAagsB32Keyless() (*AagsB32, error) {
	ob, err := NewObKeyless("aags.b32")
	if err != nil {
		return nil, err
	}
	return &AagsB32{ob}, nil
}

// Enc encrypts and encodes plaintext to obtext.
func (c *AagsB32) Enc(plaintext string) (string, error) { return c.ob.Enc(plaintext) }

// Dec decodes and decrypts obtext to plaintext.
func (c *AagsB32) Dec(obtext string) (string, error) { return c.ob.Dec(obtext) }

// Format returns the fixed format (scheme + encoding).
func (c *AagsB32) Format() Format { return c.ob.Format() }

// Scheme returns the fixed scheme.
func (c *AagsB32) Scheme() Scheme { return c.ob.Scheme() }

// Encoding returns the fixed encoding.
func (c *AagsB32) Encoding() Encoding { return c.ob.Encoding() }

var _ Codec = (*AagsB32)(nil)

// AagsB64 is the fixed-format codec for "aags.b64". The encoding is part of the
// type name and never optional.
type AagsB64 struct{ ob *Ob }

// NewAagsB64 creates a AagsB64 from a key string.
func NewAagsB64(key string) (*AagsB64, error) {
	ob, err := New("aags.b64", key)
	if err != nil {
		return nil, err
	}
	return &AagsB64{ob}, nil
}

// NewAagsB64FromBytes creates a AagsB64 from a raw key byte slice.
func NewAagsB64FromBytes(key []byte) (*AagsB64, error) {
	ob, err := NewObFromBytes("aags.b64", key)
	if err != nil {
		return nil, err
	}
	return &AagsB64{ob}, nil
}

// NewAagsB64Keyless creates a AagsB64 with the hardcoded key (testing only — NOT SECURE).
func NewAagsB64Keyless() (*AagsB64, error) {
	ob, err := NewObKeyless("aags.b64")
	if err != nil {
		return nil, err
	}
	return &AagsB64{ob}, nil
}

// Enc encrypts and encodes plaintext to obtext.
func (c *AagsB64) Enc(plaintext string) (string, error) { return c.ob.Enc(plaintext) }

// Dec decodes and decrypts obtext to plaintext.
func (c *AagsB64) Dec(obtext string) (string, error) { return c.ob.Dec(obtext) }

// Format returns the fixed format (scheme + encoding).
func (c *AagsB64) Format() Format { return c.ob.Format() }

// Scheme returns the fixed scheme.
func (c *AagsB64) Scheme() Scheme { return c.ob.Scheme() }

// Encoding returns the fixed encoding.
func (c *AagsB64) Encoding() Encoding { return c.ob.Encoding() }

var _ Codec = (*AagsB64)(nil)

// AagsHex is the fixed-format codec for "aags.hex". The encoding is part of the
// type name and never optional.
type AagsHex struct{ ob *Ob }

// NewAagsHex creates a AagsHex from a key string.
func NewAagsHex(key string) (*AagsHex, error) {
	ob, err := New("aags.hex", key)
	if err != nil {
		return nil, err
	}
	return &AagsHex{ob}, nil
}

// NewAagsHexFromBytes creates a AagsHex from a raw key byte slice.
func NewAagsHexFromBytes(key []byte) (*AagsHex, error) {
	ob, err := NewObFromBytes("aags.hex", key)
	if err != nil {
		return nil, err
	}
	return &AagsHex{ob}, nil
}

// NewAagsHexKeyless creates a AagsHex with the hardcoded key (testing only — NOT SECURE).
func NewAagsHexKeyless() (*AagsHex, error) {
	ob, err := NewObKeyless("aags.hex")
	if err != nil {
		return nil, err
	}
	return &AagsHex{ob}, nil
}

// Enc encrypts and encodes plaintext to obtext.
func (c *AagsHex) Enc(plaintext string) (string, error) { return c.ob.Enc(plaintext) }

// Dec decodes and decrypts obtext to plaintext.
func (c *AagsHex) Dec(obtext string) (string, error) { return c.ob.Dec(obtext) }

// Format returns the fixed format (scheme + encoding).
func (c *AagsHex) Format() Format { return c.ob.Format() }

// Scheme returns the fixed scheme.
func (c *AagsHex) Scheme() Scheme { return c.ob.Scheme() }

// Encoding returns the fixed encoding.
func (c *AagsHex) Encoding() Encoding { return c.ob.Encoding() }

var _ Codec = (*AagsHex)(nil)

// AasvC32 is the fixed-format codec for "aasv.c32". The encoding is part of the
// type name and never optional.
type AasvC32 struct{ ob *Ob }

// NewAasvC32 creates a AasvC32 from a key string.
func NewAasvC32(key string) (*AasvC32, error) {
	ob, err := New("aasv.c32", key)
	if err != nil {
		return nil, err
	}
	return &AasvC32{ob}, nil
}

// NewAasvC32FromBytes creates a AasvC32 from a raw key byte slice.
func NewAasvC32FromBytes(key []byte) (*AasvC32, error) {
	ob, err := NewObFromBytes("aasv.c32", key)
	if err != nil {
		return nil, err
	}
	return &AasvC32{ob}, nil
}

// NewAasvC32Keyless creates a AasvC32 with the hardcoded key (testing only — NOT SECURE).
func NewAasvC32Keyless() (*AasvC32, error) {
	ob, err := NewObKeyless("aasv.c32")
	if err != nil {
		return nil, err
	}
	return &AasvC32{ob}, nil
}

// Enc encrypts and encodes plaintext to obtext.
func (c *AasvC32) Enc(plaintext string) (string, error) { return c.ob.Enc(plaintext) }

// Dec decodes and decrypts obtext to plaintext.
func (c *AasvC32) Dec(obtext string) (string, error) { return c.ob.Dec(obtext) }

// Format returns the fixed format (scheme + encoding).
func (c *AasvC32) Format() Format { return c.ob.Format() }

// Scheme returns the fixed scheme.
func (c *AasvC32) Scheme() Scheme { return c.ob.Scheme() }

// Encoding returns the fixed encoding.
func (c *AasvC32) Encoding() Encoding { return c.ob.Encoding() }

var _ Codec = (*AasvC32)(nil)

// AasvB32 is the fixed-format codec for "aasv.b32". The encoding is part of the
// type name and never optional.
type AasvB32 struct{ ob *Ob }

// NewAasvB32 creates a AasvB32 from a key string.
func NewAasvB32(key string) (*AasvB32, error) {
	ob, err := New("aasv.b32", key)
	if err != nil {
		return nil, err
	}
	return &AasvB32{ob}, nil
}

// NewAasvB32FromBytes creates a AasvB32 from a raw key byte slice.
func NewAasvB32FromBytes(key []byte) (*AasvB32, error) {
	ob, err := NewObFromBytes("aasv.b32", key)
	if err != nil {
		return nil, err
	}
	return &AasvB32{ob}, nil
}

// NewAasvB32Keyless creates a AasvB32 with the hardcoded key (testing only — NOT SECURE).
func NewAasvB32Keyless() (*AasvB32, error) {
	ob, err := NewObKeyless("aasv.b32")
	if err != nil {
		return nil, err
	}
	return &AasvB32{ob}, nil
}

// Enc encrypts and encodes plaintext to obtext.
func (c *AasvB32) Enc(plaintext string) (string, error) { return c.ob.Enc(plaintext) }

// Dec decodes and decrypts obtext to plaintext.
func (c *AasvB32) Dec(obtext string) (string, error) { return c.ob.Dec(obtext) }

// Format returns the fixed format (scheme + encoding).
func (c *AasvB32) Format() Format { return c.ob.Format() }

// Scheme returns the fixed scheme.
func (c *AasvB32) Scheme() Scheme { return c.ob.Scheme() }

// Encoding returns the fixed encoding.
func (c *AasvB32) Encoding() Encoding { return c.ob.Encoding() }

var _ Codec = (*AasvB32)(nil)

// AasvB64 is the fixed-format codec for "aasv.b64". The encoding is part of the
// type name and never optional.
type AasvB64 struct{ ob *Ob }

// NewAasvB64 creates a AasvB64 from a key string.
func NewAasvB64(key string) (*AasvB64, error) {
	ob, err := New("aasv.b64", key)
	if err != nil {
		return nil, err
	}
	return &AasvB64{ob}, nil
}

// NewAasvB64FromBytes creates a AasvB64 from a raw key byte slice.
func NewAasvB64FromBytes(key []byte) (*AasvB64, error) {
	ob, err := NewObFromBytes("aasv.b64", key)
	if err != nil {
		return nil, err
	}
	return &AasvB64{ob}, nil
}

// NewAasvB64Keyless creates a AasvB64 with the hardcoded key (testing only — NOT SECURE).
func NewAasvB64Keyless() (*AasvB64, error) {
	ob, err := NewObKeyless("aasv.b64")
	if err != nil {
		return nil, err
	}
	return &AasvB64{ob}, nil
}

// Enc encrypts and encodes plaintext to obtext.
func (c *AasvB64) Enc(plaintext string) (string, error) { return c.ob.Enc(plaintext) }

// Dec decodes and decrypts obtext to plaintext.
func (c *AasvB64) Dec(obtext string) (string, error) { return c.ob.Dec(obtext) }

// Format returns the fixed format (scheme + encoding).
func (c *AasvB64) Format() Format { return c.ob.Format() }

// Scheme returns the fixed scheme.
func (c *AasvB64) Scheme() Scheme { return c.ob.Scheme() }

// Encoding returns the fixed encoding.
func (c *AasvB64) Encoding() Encoding { return c.ob.Encoding() }

var _ Codec = (*AasvB64)(nil)

// AasvHex is the fixed-format codec for "aasv.hex". The encoding is part of the
// type name and never optional.
type AasvHex struct{ ob *Ob }

// NewAasvHex creates a AasvHex from a key string.
func NewAasvHex(key string) (*AasvHex, error) {
	ob, err := New("aasv.hex", key)
	if err != nil {
		return nil, err
	}
	return &AasvHex{ob}, nil
}

// NewAasvHexFromBytes creates a AasvHex from a raw key byte slice.
func NewAasvHexFromBytes(key []byte) (*AasvHex, error) {
	ob, err := NewObFromBytes("aasv.hex", key)
	if err != nil {
		return nil, err
	}
	return &AasvHex{ob}, nil
}

// NewAasvHexKeyless creates a AasvHex with the hardcoded key (testing only — NOT SECURE).
func NewAasvHexKeyless() (*AasvHex, error) {
	ob, err := NewObKeyless("aasv.hex")
	if err != nil {
		return nil, err
	}
	return &AasvHex{ob}, nil
}

// Enc encrypts and encodes plaintext to obtext.
func (c *AasvHex) Enc(plaintext string) (string, error) { return c.ob.Enc(plaintext) }

// Dec decodes and decrypts obtext to plaintext.
func (c *AasvHex) Dec(obtext string) (string, error) { return c.ob.Dec(obtext) }

// Format returns the fixed format (scheme + encoding).
func (c *AasvHex) Format() Format { return c.ob.Format() }

// Scheme returns the fixed scheme.
func (c *AasvHex) Scheme() Scheme { return c.ob.Scheme() }

// Encoding returns the fixed encoding.
func (c *AasvHex) Encoding() Encoding { return c.ob.Encoding() }

var _ Codec = (*AasvHex)(nil)

// ApgsC32 is the fixed-format codec for "apgs.c32". The encoding is part of the
// type name and never optional.
type ApgsC32 struct{ ob *Ob }

// NewApgsC32 creates a ApgsC32 from a key string.
func NewApgsC32(key string) (*ApgsC32, error) {
	ob, err := New("apgs.c32", key)
	if err != nil {
		return nil, err
	}
	return &ApgsC32{ob}, nil
}

// NewApgsC32FromBytes creates a ApgsC32 from a raw key byte slice.
func NewApgsC32FromBytes(key []byte) (*ApgsC32, error) {
	ob, err := NewObFromBytes("apgs.c32", key)
	if err != nil {
		return nil, err
	}
	return &ApgsC32{ob}, nil
}

// NewApgsC32Keyless creates a ApgsC32 with the hardcoded key (testing only — NOT SECURE).
func NewApgsC32Keyless() (*ApgsC32, error) {
	ob, err := NewObKeyless("apgs.c32")
	if err != nil {
		return nil, err
	}
	return &ApgsC32{ob}, nil
}

// Enc encrypts and encodes plaintext to obtext.
func (c *ApgsC32) Enc(plaintext string) (string, error) { return c.ob.Enc(plaintext) }

// Dec decodes and decrypts obtext to plaintext.
func (c *ApgsC32) Dec(obtext string) (string, error) { return c.ob.Dec(obtext) }

// Format returns the fixed format (scheme + encoding).
func (c *ApgsC32) Format() Format { return c.ob.Format() }

// Scheme returns the fixed scheme.
func (c *ApgsC32) Scheme() Scheme { return c.ob.Scheme() }

// Encoding returns the fixed encoding.
func (c *ApgsC32) Encoding() Encoding { return c.ob.Encoding() }

var _ Codec = (*ApgsC32)(nil)

// ApgsB32 is the fixed-format codec for "apgs.b32". The encoding is part of the
// type name and never optional.
type ApgsB32 struct{ ob *Ob }

// NewApgsB32 creates a ApgsB32 from a key string.
func NewApgsB32(key string) (*ApgsB32, error) {
	ob, err := New("apgs.b32", key)
	if err != nil {
		return nil, err
	}
	return &ApgsB32{ob}, nil
}

// NewApgsB32FromBytes creates a ApgsB32 from a raw key byte slice.
func NewApgsB32FromBytes(key []byte) (*ApgsB32, error) {
	ob, err := NewObFromBytes("apgs.b32", key)
	if err != nil {
		return nil, err
	}
	return &ApgsB32{ob}, nil
}

// NewApgsB32Keyless creates a ApgsB32 with the hardcoded key (testing only — NOT SECURE).
func NewApgsB32Keyless() (*ApgsB32, error) {
	ob, err := NewObKeyless("apgs.b32")
	if err != nil {
		return nil, err
	}
	return &ApgsB32{ob}, nil
}

// Enc encrypts and encodes plaintext to obtext.
func (c *ApgsB32) Enc(plaintext string) (string, error) { return c.ob.Enc(plaintext) }

// Dec decodes and decrypts obtext to plaintext.
func (c *ApgsB32) Dec(obtext string) (string, error) { return c.ob.Dec(obtext) }

// Format returns the fixed format (scheme + encoding).
func (c *ApgsB32) Format() Format { return c.ob.Format() }

// Scheme returns the fixed scheme.
func (c *ApgsB32) Scheme() Scheme { return c.ob.Scheme() }

// Encoding returns the fixed encoding.
func (c *ApgsB32) Encoding() Encoding { return c.ob.Encoding() }

var _ Codec = (*ApgsB32)(nil)

// ApgsB64 is the fixed-format codec for "apgs.b64". The encoding is part of the
// type name and never optional.
type ApgsB64 struct{ ob *Ob }

// NewApgsB64 creates a ApgsB64 from a key string.
func NewApgsB64(key string) (*ApgsB64, error) {
	ob, err := New("apgs.b64", key)
	if err != nil {
		return nil, err
	}
	return &ApgsB64{ob}, nil
}

// NewApgsB64FromBytes creates a ApgsB64 from a raw key byte slice.
func NewApgsB64FromBytes(key []byte) (*ApgsB64, error) {
	ob, err := NewObFromBytes("apgs.b64", key)
	if err != nil {
		return nil, err
	}
	return &ApgsB64{ob}, nil
}

// NewApgsB64Keyless creates a ApgsB64 with the hardcoded key (testing only — NOT SECURE).
func NewApgsB64Keyless() (*ApgsB64, error) {
	ob, err := NewObKeyless("apgs.b64")
	if err != nil {
		return nil, err
	}
	return &ApgsB64{ob}, nil
}

// Enc encrypts and encodes plaintext to obtext.
func (c *ApgsB64) Enc(plaintext string) (string, error) { return c.ob.Enc(plaintext) }

// Dec decodes and decrypts obtext to plaintext.
func (c *ApgsB64) Dec(obtext string) (string, error) { return c.ob.Dec(obtext) }

// Format returns the fixed format (scheme + encoding).
func (c *ApgsB64) Format() Format { return c.ob.Format() }

// Scheme returns the fixed scheme.
func (c *ApgsB64) Scheme() Scheme { return c.ob.Scheme() }

// Encoding returns the fixed encoding.
func (c *ApgsB64) Encoding() Encoding { return c.ob.Encoding() }

var _ Codec = (*ApgsB64)(nil)

// ApgsHex is the fixed-format codec for "apgs.hex". The encoding is part of the
// type name and never optional.
type ApgsHex struct{ ob *Ob }

// NewApgsHex creates a ApgsHex from a key string.
func NewApgsHex(key string) (*ApgsHex, error) {
	ob, err := New("apgs.hex", key)
	if err != nil {
		return nil, err
	}
	return &ApgsHex{ob}, nil
}

// NewApgsHexFromBytes creates a ApgsHex from a raw key byte slice.
func NewApgsHexFromBytes(key []byte) (*ApgsHex, error) {
	ob, err := NewObFromBytes("apgs.hex", key)
	if err != nil {
		return nil, err
	}
	return &ApgsHex{ob}, nil
}

// NewApgsHexKeyless creates a ApgsHex with the hardcoded key (testing only — NOT SECURE).
func NewApgsHexKeyless() (*ApgsHex, error) {
	ob, err := NewObKeyless("apgs.hex")
	if err != nil {
		return nil, err
	}
	return &ApgsHex{ob}, nil
}

// Enc encrypts and encodes plaintext to obtext.
func (c *ApgsHex) Enc(plaintext string) (string, error) { return c.ob.Enc(plaintext) }

// Dec decodes and decrypts obtext to plaintext.
func (c *ApgsHex) Dec(obtext string) (string, error) { return c.ob.Dec(obtext) }

// Format returns the fixed format (scheme + encoding).
func (c *ApgsHex) Format() Format { return c.ob.Format() }

// Scheme returns the fixed scheme.
func (c *ApgsHex) Scheme() Scheme { return c.ob.Scheme() }

// Encoding returns the fixed encoding.
func (c *ApgsHex) Encoding() Encoding { return c.ob.Encoding() }

var _ Codec = (*ApgsHex)(nil)

// ApsvC32 is the fixed-format codec for "apsv.c32". The encoding is part of the
// type name and never optional.
type ApsvC32 struct{ ob *Ob }

// NewApsvC32 creates a ApsvC32 from a key string.
func NewApsvC32(key string) (*ApsvC32, error) {
	ob, err := New("apsv.c32", key)
	if err != nil {
		return nil, err
	}
	return &ApsvC32{ob}, nil
}

// NewApsvC32FromBytes creates a ApsvC32 from a raw key byte slice.
func NewApsvC32FromBytes(key []byte) (*ApsvC32, error) {
	ob, err := NewObFromBytes("apsv.c32", key)
	if err != nil {
		return nil, err
	}
	return &ApsvC32{ob}, nil
}

// NewApsvC32Keyless creates a ApsvC32 with the hardcoded key (testing only — NOT SECURE).
func NewApsvC32Keyless() (*ApsvC32, error) {
	ob, err := NewObKeyless("apsv.c32")
	if err != nil {
		return nil, err
	}
	return &ApsvC32{ob}, nil
}

// Enc encrypts and encodes plaintext to obtext.
func (c *ApsvC32) Enc(plaintext string) (string, error) { return c.ob.Enc(plaintext) }

// Dec decodes and decrypts obtext to plaintext.
func (c *ApsvC32) Dec(obtext string) (string, error) { return c.ob.Dec(obtext) }

// Format returns the fixed format (scheme + encoding).
func (c *ApsvC32) Format() Format { return c.ob.Format() }

// Scheme returns the fixed scheme.
func (c *ApsvC32) Scheme() Scheme { return c.ob.Scheme() }

// Encoding returns the fixed encoding.
func (c *ApsvC32) Encoding() Encoding { return c.ob.Encoding() }

var _ Codec = (*ApsvC32)(nil)

// ApsvB32 is the fixed-format codec for "apsv.b32". The encoding is part of the
// type name and never optional.
type ApsvB32 struct{ ob *Ob }

// NewApsvB32 creates a ApsvB32 from a key string.
func NewApsvB32(key string) (*ApsvB32, error) {
	ob, err := New("apsv.b32", key)
	if err != nil {
		return nil, err
	}
	return &ApsvB32{ob}, nil
}

// NewApsvB32FromBytes creates a ApsvB32 from a raw key byte slice.
func NewApsvB32FromBytes(key []byte) (*ApsvB32, error) {
	ob, err := NewObFromBytes("apsv.b32", key)
	if err != nil {
		return nil, err
	}
	return &ApsvB32{ob}, nil
}

// NewApsvB32Keyless creates a ApsvB32 with the hardcoded key (testing only — NOT SECURE).
func NewApsvB32Keyless() (*ApsvB32, error) {
	ob, err := NewObKeyless("apsv.b32")
	if err != nil {
		return nil, err
	}
	return &ApsvB32{ob}, nil
}

// Enc encrypts and encodes plaintext to obtext.
func (c *ApsvB32) Enc(plaintext string) (string, error) { return c.ob.Enc(plaintext) }

// Dec decodes and decrypts obtext to plaintext.
func (c *ApsvB32) Dec(obtext string) (string, error) { return c.ob.Dec(obtext) }

// Format returns the fixed format (scheme + encoding).
func (c *ApsvB32) Format() Format { return c.ob.Format() }

// Scheme returns the fixed scheme.
func (c *ApsvB32) Scheme() Scheme { return c.ob.Scheme() }

// Encoding returns the fixed encoding.
func (c *ApsvB32) Encoding() Encoding { return c.ob.Encoding() }

var _ Codec = (*ApsvB32)(nil)

// ApsvB64 is the fixed-format codec for "apsv.b64". The encoding is part of the
// type name and never optional.
type ApsvB64 struct{ ob *Ob }

// NewApsvB64 creates a ApsvB64 from a key string.
func NewApsvB64(key string) (*ApsvB64, error) {
	ob, err := New("apsv.b64", key)
	if err != nil {
		return nil, err
	}
	return &ApsvB64{ob}, nil
}

// NewApsvB64FromBytes creates a ApsvB64 from a raw key byte slice.
func NewApsvB64FromBytes(key []byte) (*ApsvB64, error) {
	ob, err := NewObFromBytes("apsv.b64", key)
	if err != nil {
		return nil, err
	}
	return &ApsvB64{ob}, nil
}

// NewApsvB64Keyless creates a ApsvB64 with the hardcoded key (testing only — NOT SECURE).
func NewApsvB64Keyless() (*ApsvB64, error) {
	ob, err := NewObKeyless("apsv.b64")
	if err != nil {
		return nil, err
	}
	return &ApsvB64{ob}, nil
}

// Enc encrypts and encodes plaintext to obtext.
func (c *ApsvB64) Enc(plaintext string) (string, error) { return c.ob.Enc(plaintext) }

// Dec decodes and decrypts obtext to plaintext.
func (c *ApsvB64) Dec(obtext string) (string, error) { return c.ob.Dec(obtext) }

// Format returns the fixed format (scheme + encoding).
func (c *ApsvB64) Format() Format { return c.ob.Format() }

// Scheme returns the fixed scheme.
func (c *ApsvB64) Scheme() Scheme { return c.ob.Scheme() }

// Encoding returns the fixed encoding.
func (c *ApsvB64) Encoding() Encoding { return c.ob.Encoding() }

var _ Codec = (*ApsvB64)(nil)

// ApsvHex is the fixed-format codec for "apsv.hex". The encoding is part of the
// type name and never optional.
type ApsvHex struct{ ob *Ob }

// NewApsvHex creates a ApsvHex from a key string.
func NewApsvHex(key string) (*ApsvHex, error) {
	ob, err := New("apsv.hex", key)
	if err != nil {
		return nil, err
	}
	return &ApsvHex{ob}, nil
}

// NewApsvHexFromBytes creates a ApsvHex from a raw key byte slice.
func NewApsvHexFromBytes(key []byte) (*ApsvHex, error) {
	ob, err := NewObFromBytes("apsv.hex", key)
	if err != nil {
		return nil, err
	}
	return &ApsvHex{ob}, nil
}

// NewApsvHexKeyless creates a ApsvHex with the hardcoded key (testing only — NOT SECURE).
func NewApsvHexKeyless() (*ApsvHex, error) {
	ob, err := NewObKeyless("apsv.hex")
	if err != nil {
		return nil, err
	}
	return &ApsvHex{ob}, nil
}

// Enc encrypts and encodes plaintext to obtext.
func (c *ApsvHex) Enc(plaintext string) (string, error) { return c.ob.Enc(plaintext) }

// Dec decodes and decrypts obtext to plaintext.
func (c *ApsvHex) Dec(obtext string) (string, error) { return c.ob.Dec(obtext) }

// Format returns the fixed format (scheme + encoding).
func (c *ApsvHex) Format() Format { return c.ob.Format() }

// Scheme returns the fixed scheme.
func (c *ApsvHex) Scheme() Scheme { return c.ob.Scheme() }

// Encoding returns the fixed encoding.
func (c *ApsvHex) Encoding() Encoding { return c.ob.Encoding() }

var _ Codec = (*ApsvHex)(nil)

// UpbcC32 is the fixed-format codec for "upbc.c32". The encoding is part of the
// type name and never optional.
type UpbcC32 struct{ ob *Ob }

// NewUpbcC32 creates a UpbcC32 from a key string.
func NewUpbcC32(key string) (*UpbcC32, error) {
	ob, err := New("upbc.c32", key)
	if err != nil {
		return nil, err
	}
	return &UpbcC32{ob}, nil
}

// NewUpbcC32FromBytes creates a UpbcC32 from a raw key byte slice.
func NewUpbcC32FromBytes(key []byte) (*UpbcC32, error) {
	ob, err := NewObFromBytes("upbc.c32", key)
	if err != nil {
		return nil, err
	}
	return &UpbcC32{ob}, nil
}

// NewUpbcC32Keyless creates a UpbcC32 with the hardcoded key (testing only — NOT SECURE).
func NewUpbcC32Keyless() (*UpbcC32, error) {
	ob, err := NewObKeyless("upbc.c32")
	if err != nil {
		return nil, err
	}
	return &UpbcC32{ob}, nil
}

// Enc encrypts and encodes plaintext to obtext.
func (c *UpbcC32) Enc(plaintext string) (string, error) { return c.ob.Enc(plaintext) }

// Dec decodes and decrypts obtext to plaintext.
func (c *UpbcC32) Dec(obtext string) (string, error) { return c.ob.Dec(obtext) }

// Format returns the fixed format (scheme + encoding).
func (c *UpbcC32) Format() Format { return c.ob.Format() }

// Scheme returns the fixed scheme.
func (c *UpbcC32) Scheme() Scheme { return c.ob.Scheme() }

// Encoding returns the fixed encoding.
func (c *UpbcC32) Encoding() Encoding { return c.ob.Encoding() }

var _ Codec = (*UpbcC32)(nil)

// UpbcB32 is the fixed-format codec for "upbc.b32". The encoding is part of the
// type name and never optional.
type UpbcB32 struct{ ob *Ob }

// NewUpbcB32 creates a UpbcB32 from a key string.
func NewUpbcB32(key string) (*UpbcB32, error) {
	ob, err := New("upbc.b32", key)
	if err != nil {
		return nil, err
	}
	return &UpbcB32{ob}, nil
}

// NewUpbcB32FromBytes creates a UpbcB32 from a raw key byte slice.
func NewUpbcB32FromBytes(key []byte) (*UpbcB32, error) {
	ob, err := NewObFromBytes("upbc.b32", key)
	if err != nil {
		return nil, err
	}
	return &UpbcB32{ob}, nil
}

// NewUpbcB32Keyless creates a UpbcB32 with the hardcoded key (testing only — NOT SECURE).
func NewUpbcB32Keyless() (*UpbcB32, error) {
	ob, err := NewObKeyless("upbc.b32")
	if err != nil {
		return nil, err
	}
	return &UpbcB32{ob}, nil
}

// Enc encrypts and encodes plaintext to obtext.
func (c *UpbcB32) Enc(plaintext string) (string, error) { return c.ob.Enc(plaintext) }

// Dec decodes and decrypts obtext to plaintext.
func (c *UpbcB32) Dec(obtext string) (string, error) { return c.ob.Dec(obtext) }

// Format returns the fixed format (scheme + encoding).
func (c *UpbcB32) Format() Format { return c.ob.Format() }

// Scheme returns the fixed scheme.
func (c *UpbcB32) Scheme() Scheme { return c.ob.Scheme() }

// Encoding returns the fixed encoding.
func (c *UpbcB32) Encoding() Encoding { return c.ob.Encoding() }

var _ Codec = (*UpbcB32)(nil)

// UpbcB64 is the fixed-format codec for "upbc.b64". The encoding is part of the
// type name and never optional.
type UpbcB64 struct{ ob *Ob }

// NewUpbcB64 creates a UpbcB64 from a key string.
func NewUpbcB64(key string) (*UpbcB64, error) {
	ob, err := New("upbc.b64", key)
	if err != nil {
		return nil, err
	}
	return &UpbcB64{ob}, nil
}

// NewUpbcB64FromBytes creates a UpbcB64 from a raw key byte slice.
func NewUpbcB64FromBytes(key []byte) (*UpbcB64, error) {
	ob, err := NewObFromBytes("upbc.b64", key)
	if err != nil {
		return nil, err
	}
	return &UpbcB64{ob}, nil
}

// NewUpbcB64Keyless creates a UpbcB64 with the hardcoded key (testing only — NOT SECURE).
func NewUpbcB64Keyless() (*UpbcB64, error) {
	ob, err := NewObKeyless("upbc.b64")
	if err != nil {
		return nil, err
	}
	return &UpbcB64{ob}, nil
}

// Enc encrypts and encodes plaintext to obtext.
func (c *UpbcB64) Enc(plaintext string) (string, error) { return c.ob.Enc(plaintext) }

// Dec decodes and decrypts obtext to plaintext.
func (c *UpbcB64) Dec(obtext string) (string, error) { return c.ob.Dec(obtext) }

// Format returns the fixed format (scheme + encoding).
func (c *UpbcB64) Format() Format { return c.ob.Format() }

// Scheme returns the fixed scheme.
func (c *UpbcB64) Scheme() Scheme { return c.ob.Scheme() }

// Encoding returns the fixed encoding.
func (c *UpbcB64) Encoding() Encoding { return c.ob.Encoding() }

var _ Codec = (*UpbcB64)(nil)

// UpbcHex is the fixed-format codec for "upbc.hex". The encoding is part of the
// type name and never optional.
type UpbcHex struct{ ob *Ob }

// NewUpbcHex creates a UpbcHex from a key string.
func NewUpbcHex(key string) (*UpbcHex, error) {
	ob, err := New("upbc.hex", key)
	if err != nil {
		return nil, err
	}
	return &UpbcHex{ob}, nil
}

// NewUpbcHexFromBytes creates a UpbcHex from a raw key byte slice.
func NewUpbcHexFromBytes(key []byte) (*UpbcHex, error) {
	ob, err := NewObFromBytes("upbc.hex", key)
	if err != nil {
		return nil, err
	}
	return &UpbcHex{ob}, nil
}

// NewUpbcHexKeyless creates a UpbcHex with the hardcoded key (testing only — NOT SECURE).
func NewUpbcHexKeyless() (*UpbcHex, error) {
	ob, err := NewObKeyless("upbc.hex")
	if err != nil {
		return nil, err
	}
	return &UpbcHex{ob}, nil
}

// Enc encrypts and encodes plaintext to obtext.
func (c *UpbcHex) Enc(plaintext string) (string, error) { return c.ob.Enc(plaintext) }

// Dec decodes and decrypts obtext to plaintext.
func (c *UpbcHex) Dec(obtext string) (string, error) { return c.ob.Dec(obtext) }

// Format returns the fixed format (scheme + encoding).
func (c *UpbcHex) Format() Format { return c.ob.Format() }

// Scheme returns the fixed scheme.
func (c *UpbcHex) Scheme() Scheme { return c.ob.Scheme() }

// Encoding returns the fixed encoding.
func (c *UpbcHex) Encoding() Encoding { return c.ob.Encoding() }

var _ Codec = (*UpbcHex)(nil)
