// Code generated by scripts/gen-codecs; DO NOT EDIT.

package obu

import "oboron.org/go/oboron"

// UpcbcC32 is the fixed-format codec for "upcbc.c32". The encoding is part of the
// type name and never optional.
type UpcbcC32 struct{ obu *Obu }

// NewUpcbcC32 creates a UpcbcC32 from a secret string.
func NewUpcbcC32(secret string) (*UpcbcC32, error) {
	obu, err := NewObu("upcbc.c32", secret)
	if err != nil {
		return nil, err
	}
	return &UpcbcC32{obu}, nil
}

// NewUpcbcC32FromBytes creates a UpcbcC32 from a raw secret byte slice.
func NewUpcbcC32FromBytes(secret []byte) (*UpcbcC32, error) {
	obu, err := NewObuFromBytes("upcbc.c32", secret)
	if err != nil {
		return nil, err
	}
	return &UpcbcC32{obu}, nil
}

// NewUpcbcC32Keyless creates a UpcbcC32 with the hardcoded secret (testing only — NOT SECURE).
func NewUpcbcC32Keyless() (*UpcbcC32, error) {
	obu, err := NewObuKeyless("upcbc.c32")
	if err != nil {
		return nil, err
	}
	return &UpcbcC32{obu}, nil
}

// Enc encrypts and encodes plaintext to obtext.
func (c *UpcbcC32) Enc(plaintext string) (string, error) { return c.obu.Enc(plaintext) }

// Dec decodes and decrypts obtext to plaintext.
func (c *UpcbcC32) Dec(obtext string) (string, error) { return c.obu.Dec(obtext) }

// Format returns the fixed format (scheme + encoding).
func (c *UpcbcC32) Format() oboron.Format { return c.obu.Format() }

// Scheme returns the fixed scheme.
func (c *UpcbcC32) Scheme() oboron.Scheme { return c.obu.Scheme() }

// Encoding returns the fixed encoding.
func (c *UpcbcC32) Encoding() oboron.Encoding { return c.obu.Encoding() }

var _ oboron.Codec = (*UpcbcC32)(nil)

// UpcbcB32 is the fixed-format codec for "upcbc.b32". The encoding is part of the
// type name and never optional.
type UpcbcB32 struct{ obu *Obu }

// NewUpcbcB32 creates a UpcbcB32 from a secret string.
func NewUpcbcB32(secret string) (*UpcbcB32, error) {
	obu, err := NewObu("upcbc.b32", secret)
	if err != nil {
		return nil, err
	}
	return &UpcbcB32{obu}, nil
}

// NewUpcbcB32FromBytes creates a UpcbcB32 from a raw secret byte slice.
func NewUpcbcB32FromBytes(secret []byte) (*UpcbcB32, error) {
	obu, err := NewObuFromBytes("upcbc.b32", secret)
	if err != nil {
		return nil, err
	}
	return &UpcbcB32{obu}, nil
}

// NewUpcbcB32Keyless creates a UpcbcB32 with the hardcoded secret (testing only — NOT SECURE).
func NewUpcbcB32Keyless() (*UpcbcB32, error) {
	obu, err := NewObuKeyless("upcbc.b32")
	if err != nil {
		return nil, err
	}
	return &UpcbcB32{obu}, nil
}

// Enc encrypts and encodes plaintext to obtext.
func (c *UpcbcB32) Enc(plaintext string) (string, error) { return c.obu.Enc(plaintext) }

// Dec decodes and decrypts obtext to plaintext.
func (c *UpcbcB32) Dec(obtext string) (string, error) { return c.obu.Dec(obtext) }

// Format returns the fixed format (scheme + encoding).
func (c *UpcbcB32) Format() oboron.Format { return c.obu.Format() }

// Scheme returns the fixed scheme.
func (c *UpcbcB32) Scheme() oboron.Scheme { return c.obu.Scheme() }

// Encoding returns the fixed encoding.
func (c *UpcbcB32) Encoding() oboron.Encoding { return c.obu.Encoding() }

var _ oboron.Codec = (*UpcbcB32)(nil)

// UpcbcB64 is the fixed-format codec for "upcbc.b64". The encoding is part of the
// type name and never optional.
type UpcbcB64 struct{ obu *Obu }

// NewUpcbcB64 creates a UpcbcB64 from a secret string.
func NewUpcbcB64(secret string) (*UpcbcB64, error) {
	obu, err := NewObu("upcbc.b64", secret)
	if err != nil {
		return nil, err
	}
	return &UpcbcB64{obu}, nil
}

// NewUpcbcB64FromBytes creates a UpcbcB64 from a raw secret byte slice.
func NewUpcbcB64FromBytes(secret []byte) (*UpcbcB64, error) {
	obu, err := NewObuFromBytes("upcbc.b64", secret)
	if err != nil {
		return nil, err
	}
	return &UpcbcB64{obu}, nil
}

// NewUpcbcB64Keyless creates a UpcbcB64 with the hardcoded secret (testing only — NOT SECURE).
func NewUpcbcB64Keyless() (*UpcbcB64, error) {
	obu, err := NewObuKeyless("upcbc.b64")
	if err != nil {
		return nil, err
	}
	return &UpcbcB64{obu}, nil
}

// Enc encrypts and encodes plaintext to obtext.
func (c *UpcbcB64) Enc(plaintext string) (string, error) { return c.obu.Enc(plaintext) }

// Dec decodes and decrypts obtext to plaintext.
func (c *UpcbcB64) Dec(obtext string) (string, error) { return c.obu.Dec(obtext) }

// Format returns the fixed format (scheme + encoding).
func (c *UpcbcB64) Format() oboron.Format { return c.obu.Format() }

// Scheme returns the fixed scheme.
func (c *UpcbcB64) Scheme() oboron.Scheme { return c.obu.Scheme() }

// Encoding returns the fixed encoding.
func (c *UpcbcB64) Encoding() oboron.Encoding { return c.obu.Encoding() }

var _ oboron.Codec = (*UpcbcB64)(nil)

// UpcbcHex is the fixed-format codec for "upcbc.hex". The encoding is part of the
// type name and never optional.
type UpcbcHex struct{ obu *Obu }

// NewUpcbcHex creates a UpcbcHex from a secret string.
func NewUpcbcHex(secret string) (*UpcbcHex, error) {
	obu, err := NewObu("upcbc.hex", secret)
	if err != nil {
		return nil, err
	}
	return &UpcbcHex{obu}, nil
}

// NewUpcbcHexFromBytes creates a UpcbcHex from a raw secret byte slice.
func NewUpcbcHexFromBytes(secret []byte) (*UpcbcHex, error) {
	obu, err := NewObuFromBytes("upcbc.hex", secret)
	if err != nil {
		return nil, err
	}
	return &UpcbcHex{obu}, nil
}

// NewUpcbcHexKeyless creates a UpcbcHex with the hardcoded secret (testing only — NOT SECURE).
func NewUpcbcHexKeyless() (*UpcbcHex, error) {
	obu, err := NewObuKeyless("upcbc.hex")
	if err != nil {
		return nil, err
	}
	return &UpcbcHex{obu}, nil
}

// Enc encrypts and encodes plaintext to obtext.
func (c *UpcbcHex) Enc(plaintext string) (string, error) { return c.obu.Enc(plaintext) }

// Dec decodes and decrypts obtext to plaintext.
func (c *UpcbcHex) Dec(obtext string) (string, error) { return c.obu.Dec(obtext) }

// Format returns the fixed format (scheme + encoding).
func (c *UpcbcHex) Format() oboron.Format { return c.obu.Format() }

// Scheme returns the fixed scheme.
func (c *UpcbcHex) Scheme() oboron.Scheme { return c.obu.Scheme() }

// Encoding returns the fixed encoding.
func (c *UpcbcHex) Encoding() oboron.Encoding { return c.obu.Encoding() }

var _ oboron.Codec = (*UpcbcHex)(nil)

// ZdcbcC32 is the fixed-format codec for "zdcbc.c32". The encoding is part of the
// type name and never optional.
type ZdcbcC32 struct{ obu *Obu }

// NewZdcbcC32 creates a ZdcbcC32 from a secret string.
func NewZdcbcC32(secret string) (*ZdcbcC32, error) {
	obu, err := NewObu("zdcbc.c32", secret)
	if err != nil {
		return nil, err
	}
	return &ZdcbcC32{obu}, nil
}

// NewZdcbcC32FromBytes creates a ZdcbcC32 from a raw secret byte slice.
func NewZdcbcC32FromBytes(secret []byte) (*ZdcbcC32, error) {
	obu, err := NewObuFromBytes("zdcbc.c32", secret)
	if err != nil {
		return nil, err
	}
	return &ZdcbcC32{obu}, nil
}

// NewZdcbcC32Keyless creates a ZdcbcC32 with the hardcoded secret (testing only — NOT SECURE).
func NewZdcbcC32Keyless() (*ZdcbcC32, error) {
	obu, err := NewObuKeyless("zdcbc.c32")
	if err != nil {
		return nil, err
	}
	return &ZdcbcC32{obu}, nil
}

// Enc encrypts and encodes plaintext to obtext.
func (c *ZdcbcC32) Enc(plaintext string) (string, error) { return c.obu.Enc(plaintext) }

// Dec decodes and decrypts obtext to plaintext.
func (c *ZdcbcC32) Dec(obtext string) (string, error) { return c.obu.Dec(obtext) }

// Format returns the fixed format (scheme + encoding).
func (c *ZdcbcC32) Format() oboron.Format { return c.obu.Format() }

// Scheme returns the fixed scheme.
func (c *ZdcbcC32) Scheme() oboron.Scheme { return c.obu.Scheme() }

// Encoding returns the fixed encoding.
func (c *ZdcbcC32) Encoding() oboron.Encoding { return c.obu.Encoding() }

var _ oboron.Codec = (*ZdcbcC32)(nil)

// ZdcbcB32 is the fixed-format codec for "zdcbc.b32". The encoding is part of the
// type name and never optional.
type ZdcbcB32 struct{ obu *Obu }

// NewZdcbcB32 creates a ZdcbcB32 from a secret string.
func NewZdcbcB32(secret string) (*ZdcbcB32, error) {
	obu, err := NewObu("zdcbc.b32", secret)
	if err != nil {
		return nil, err
	}
	return &ZdcbcB32{obu}, nil
}

// NewZdcbcB32FromBytes creates a ZdcbcB32 from a raw secret byte slice.
func NewZdcbcB32FromBytes(secret []byte) (*ZdcbcB32, error) {
	obu, err := NewObuFromBytes("zdcbc.b32", secret)
	if err != nil {
		return nil, err
	}
	return &ZdcbcB32{obu}, nil
}

// NewZdcbcB32Keyless creates a ZdcbcB32 with the hardcoded secret (testing only — NOT SECURE).
func NewZdcbcB32Keyless() (*ZdcbcB32, error) {
	obu, err := NewObuKeyless("zdcbc.b32")
	if err != nil {
		return nil, err
	}
	return &ZdcbcB32{obu}, nil
}

// Enc encrypts and encodes plaintext to obtext.
func (c *ZdcbcB32) Enc(plaintext string) (string, error) { return c.obu.Enc(plaintext) }

// Dec decodes and decrypts obtext to plaintext.
func (c *ZdcbcB32) Dec(obtext string) (string, error) { return c.obu.Dec(obtext) }

// Format returns the fixed format (scheme + encoding).
func (c *ZdcbcB32) Format() oboron.Format { return c.obu.Format() }

// Scheme returns the fixed scheme.
func (c *ZdcbcB32) Scheme() oboron.Scheme { return c.obu.Scheme() }

// Encoding returns the fixed encoding.
func (c *ZdcbcB32) Encoding() oboron.Encoding { return c.obu.Encoding() }

var _ oboron.Codec = (*ZdcbcB32)(nil)

// ZdcbcB64 is the fixed-format codec for "zdcbc.b64". The encoding is part of the
// type name and never optional.
type ZdcbcB64 struct{ obu *Obu }

// NewZdcbcB64 creates a ZdcbcB64 from a secret string.
func NewZdcbcB64(secret string) (*ZdcbcB64, error) {
	obu, err := NewObu("zdcbc.b64", secret)
	if err != nil {
		return nil, err
	}
	return &ZdcbcB64{obu}, nil
}

// NewZdcbcB64FromBytes creates a ZdcbcB64 from a raw secret byte slice.
func NewZdcbcB64FromBytes(secret []byte) (*ZdcbcB64, error) {
	obu, err := NewObuFromBytes("zdcbc.b64", secret)
	if err != nil {
		return nil, err
	}
	return &ZdcbcB64{obu}, nil
}

// NewZdcbcB64Keyless creates a ZdcbcB64 with the hardcoded secret (testing only — NOT SECURE).
func NewZdcbcB64Keyless() (*ZdcbcB64, error) {
	obu, err := NewObuKeyless("zdcbc.b64")
	if err != nil {
		return nil, err
	}
	return &ZdcbcB64{obu}, nil
}

// Enc encrypts and encodes plaintext to obtext.
func (c *ZdcbcB64) Enc(plaintext string) (string, error) { return c.obu.Enc(plaintext) }

// Dec decodes and decrypts obtext to plaintext.
func (c *ZdcbcB64) Dec(obtext string) (string, error) { return c.obu.Dec(obtext) }

// Format returns the fixed format (scheme + encoding).
func (c *ZdcbcB64) Format() oboron.Format { return c.obu.Format() }

// Scheme returns the fixed scheme.
func (c *ZdcbcB64) Scheme() oboron.Scheme { return c.obu.Scheme() }

// Encoding returns the fixed encoding.
func (c *ZdcbcB64) Encoding() oboron.Encoding { return c.obu.Encoding() }

var _ oboron.Codec = (*ZdcbcB64)(nil)

// ZdcbcHex is the fixed-format codec for "zdcbc.hex". The encoding is part of the
// type name and never optional.
type ZdcbcHex struct{ obu *Obu }

// NewZdcbcHex creates a ZdcbcHex from a secret string.
func NewZdcbcHex(secret string) (*ZdcbcHex, error) {
	obu, err := NewObu("zdcbc.hex", secret)
	if err != nil {
		return nil, err
	}
	return &ZdcbcHex{obu}, nil
}

// NewZdcbcHexFromBytes creates a ZdcbcHex from a raw secret byte slice.
func NewZdcbcHexFromBytes(secret []byte) (*ZdcbcHex, error) {
	obu, err := NewObuFromBytes("zdcbc.hex", secret)
	if err != nil {
		return nil, err
	}
	return &ZdcbcHex{obu}, nil
}

// NewZdcbcHexKeyless creates a ZdcbcHex with the hardcoded secret (testing only — NOT SECURE).
func NewZdcbcHexKeyless() (*ZdcbcHex, error) {
	obu, err := NewObuKeyless("zdcbc.hex")
	if err != nil {
		return nil, err
	}
	return &ZdcbcHex{obu}, nil
}

// Enc encrypts and encodes plaintext to obtext.
func (c *ZdcbcHex) Enc(plaintext string) (string, error) { return c.obu.Enc(plaintext) }

// Dec decodes and decrypts obtext to plaintext.
func (c *ZdcbcHex) Dec(obtext string) (string, error) { return c.obu.Dec(obtext) }

// Format returns the fixed format (scheme + encoding).
func (c *ZdcbcHex) Format() oboron.Format { return c.obu.Format() }

// Scheme returns the fixed scheme.
func (c *ZdcbcHex) Scheme() oboron.Scheme { return c.obu.Scheme() }

// Encoding returns the fixed encoding.
func (c *ZdcbcHex) Encoding() oboron.Encoding { return c.obu.Encoding() }

var _ oboron.Codec = (*ZdcbcHex)(nil)
