package obu

import (
	"bufio"
	"encoding/json"
	"fmt"
	"os"
	"strings"
	"testing"
)

// vector represents a single obu test vector (format/plaintext/obtext).
type vector struct {
	Format    string `json:"format"`
	Plaintext string `json:"plaintext"`
	Obtext    string `json:"obtext"`
}

// metaEntry represents a metadata line in a vector file, if any.
type metaEntry struct {
	Type string `json:"type"`
}

func loadVectors(t *testing.T, path string) []vector {
	t.Helper()
	file, err := os.Open(path)
	if err != nil {
		t.Fatalf("Failed to open %s: %v", path, err)
	}
	defer file.Close()

	var vectors []vector
	scanner := bufio.NewScanner(file)
	scanner.Buffer(make([]byte, 0, 64*1024), 1024*1024)
	for scanner.Scan() {
		line := strings.TrimSpace(scanner.Text())
		if line == "" {
			continue
		}
		var meta metaEntry
		if json.Unmarshal([]byte(line), &meta) == nil && meta.Type == "meta" {
			continue
		}
		var v vector
		if err := json.Unmarshal([]byte(line), &v); err != nil {
			t.Fatalf("Failed to parse vector in %s: %v\nLine: %s", path, err, line)
		}
		vectors = append(vectors, v)
	}
	if err := scanner.Err(); err != nil {
		t.Fatalf("Error reading %s: %v", path, err)
	}
	return vectors
}

// schemeOf returns the scheme part of a format string ("zdcbc.c32" -> "zdcbc").
func schemeOf(format string) string { return strings.Split(format, ".")[0] }

// isDeterministic reports whether the obu scheme is deterministic.
func isDeterministic(format string) bool { return schemeOf(format) == "zdcbc" }

// TestGoldenObuVectors verifies the obu obtext vectors generated by the Rust
// reference under the shared hardcoded secret. Deterministic schemes (zdcbc)
// must reproduce the obtext exactly and decode it; probabilistic schemes
// (upcbc) decode the canned obtext and survive a fresh encode/decode round-trip.
func TestGoldenObuVectors(t *testing.T) {
	vectors := loadVectors(t, "testdata/obu-test-vectors.jsonl")
	if len(vectors) == 0 {
		t.Fatal("No obu test vectors loaded")
	}
	t.Logf("Loaded %d obu test vectors", len(vectors))

	om, err := NewOmnibuKeyless()
	if err != nil {
		t.Fatalf("NewOmnibuKeyless() failed: %v", err)
	}

	for _, v := range vectors {
		name := fmt.Sprintf("%s/%s", v.Format, truncate(v.Plaintext, 20))

		if isDeterministic(v.Format) {
			t.Run(name+"/encode", func(t *testing.T) {
				ot, err := om.Enc(v.Plaintext, v.Format)
				if err != nil {
					t.Fatalf("Enc(%q, %q) failed: %v", v.Plaintext, v.Format, err)
				}
				if ot != v.Obtext {
					t.Errorf("Enc mismatch:\n  got:      %q\n  expected: %q", ot, v.Obtext)
				}
			})
		}

		t.Run(name+"/decode", func(t *testing.T) {
			pt, err := om.Dec(v.Obtext, v.Format)
			if err != nil {
				t.Fatalf("Dec(%q, %q) failed: %v", v.Obtext, v.Format, err)
			}
			if pt != v.Plaintext {
				t.Errorf("Dec mismatch:\n  got:      %q\n  expected: %q", pt, v.Plaintext)
			}
		})

		if !isDeterministic(v.Format) {
			t.Run(name+"/roundtrip", func(t *testing.T) {
				ot, err := om.Enc(v.Plaintext, v.Format)
				if err != nil {
					t.Fatalf("Enc(%q, %q) failed: %v", v.Plaintext, v.Format, err)
				}
				pt, err := om.Dec(ot, v.Format)
				if err != nil {
					t.Fatalf("Dec(%q, %q) failed: %v", ot, v.Format, err)
				}
				if pt != v.Plaintext {
					t.Errorf("Roundtrip mismatch:\n  got:      %q\n  expected: %q", pt, v.Plaintext)
				}
			})
		}
	}
}

// TestGoldenObuRoundtrip verifies Go's own encode/decode round-trip for every
// obu scheme × encoding combination.
func TestGoldenObuRoundtrip(t *testing.T) {
	om, err := NewOmnibuKeyless()
	if err != nil {
		t.Fatalf("NewOmnibuKeyless() failed: %v", err)
	}

	formats := []string{
		"upcbc.b32", "upcbc.c32", "upcbc.b64", "upcbc.hex",
		"zdcbc.b32", "zdcbc.c32", "zdcbc.b64", "zdcbc.hex",
	}
	inputs := []string{"a", "hello", "test123", "abcdefghijklmnop", "abcdefghijklmnopqrstuvwxyz"}

	for _, format := range formats {
		for _, input := range inputs {
			name := fmt.Sprintf("%s/%s", format, truncate(input, 12))
			t.Run(name+"/roundtrip", func(t *testing.T) {
				encoded, err := om.Enc(input, format)
				if err != nil {
					t.Fatalf("Enc(%q, %q) failed: %v", input, format, err)
				}
				decoded, err := om.Dec(encoded, format)
				if err != nil {
					t.Fatalf("Dec(%q, %q) failed: %v", encoded, format, err)
				}
				if decoded != input {
					t.Errorf("Roundtrip mismatch:\n  input:   %q\n  encoded: %q\n  decoded: %q", input, encoded, decoded)
				}
			})
		}
	}
}

func truncate(s string, maxLen int) string {
	if len(s) <= maxLen {
		return s
	}
	return s[:maxLen] + "..."
}
