// Command gen-codecs generates the fixed-type codec families — the Go analog
// of Rust's impl_codec_* / impl_zcodec! macros. Each fixed type bakes a
// scheme+encoding into its name so no encoding default can ever apply, and
// wraps the matching flexible codec (*oboron.Ob or *ztier.Obz) by composition
// (not embedding) so only the Codec methods are exposed — never the setters,
// which would defeat the "encoding baked in" guarantee.
//
// Run via `go generate ./oboron/...`; the single //go:generate directive in
// oboron/ob.go invokes this with cwd = oboron/, so it writes both output
// files. Keep the committed output in sync (CI diffs it).
package main

import (
	"fmt"
	"go/format"
	"os"
	"strings"
)

type fixedType struct {
	Name   string // Go type name, e.g. "AasvC32"
	Format string // baked format string, e.g. "aasv.c32"
}

type encoding struct{ suffix, code string }

var encodings = []encoding{
	{"C32", "c32"},
	{"B32", "b32"},
	{"B64", "b64"},
	{"Hex", "hex"},
}

// a/u-tier schemes, in oboron-rs codec.rs order.
var auSchemes = []struct{ title, code string }{
	{"Aags", "aags"},
	{"Aasv", "aasv"},
	{"Apgs", "apgs"},
	{"Apsv", "apsv"},
	{"Upbc", "upbc"},
}

func main() {
	var au []fixedType
	for _, s := range auSchemes {
		for _, e := range encodings {
			au = append(au, fixedType{Name: s.title + e.suffix, Format: s.code + "." + e.code})
		}
	}

	var z []fixedType
	for _, e := range encodings {
		z = append(z, fixedType{Name: "Zrbcx" + e.suffix, Format: "zrbcx." + e.code})
	}
	// Legacy is a single fixed form with no encoding suffix.
	z = append(z, fixedType{Name: "Legacy", Format: "legacy"})

	writeFormatted("codec_fixed_gen.go", renderAU(au))
	writeFormatted("ztier/codec_fixed_gen.go", renderZ(z))
}

// tierConfig parameterizes the two near-identical renderers.
type tierConfig struct {
	pkg        string // package clause
	imports    string // import block (may be empty)
	field      string // wrapper field name: "ob" / "obz"
	wrapType   string // wrapped flexible type: "Ob" / "Obz"
	newFn      string // flexible string ctor: "New" / "NewObz"
	newBytesFn string // flexible bytes ctor: "NewObFromBytes" / "NewObzFromBytes"
	keylessFn  string // flexible keyless ctor: "NewObKeyless" / "NewObzKeyless"
	material   string // "key" / "secret" (param name)
	qual       string // return-type qualifier: "" / "oboron."
}

func renderAU(types []fixedType) string {
	return render(tierConfig{
		pkg:        "package oboron",
		imports:    "",
		field:      "ob",
		wrapType:   "Ob",
		newFn:      "New",
		newBytesFn: "NewObFromBytes",
		keylessFn:  "NewObKeyless",
		material:   "key",
		qual:       "",
	}, types)
}

func renderZ(types []fixedType) string {
	return render(tierConfig{
		pkg:        "package ztier",
		imports:    "import \"oboron.org/go/oboron\"\n",
		field:      "obz",
		wrapType:   "Obz",
		newFn:      "NewObz",
		newBytesFn: "NewObzFromBytes",
		keylessFn:  "NewObzKeyless",
		material:   "secret",
		qual:       "oboron.",
	}, types)
}

func render(c tierConfig, types []fixedType) string {
	var b strings.Builder
	b.WriteString("// Code generated by scripts/gen-codecs; DO NOT EDIT.\n\n")
	b.WriteString(c.pkg + "\n\n")
	if c.imports != "" {
		b.WriteString(c.imports + "\n")
	}

	mat := c.material // "key" / "secret"

	for _, t := range types {
		fmt.Fprintf(&b, "// %s is the fixed-format codec for %q. The encoding is part of the\n", t.Name, t.Format)
		fmt.Fprintf(&b, "// type name and never optional.\n")
		fmt.Fprintf(&b, "type %s struct{ %s *%s }\n\n", t.Name, c.field, c.wrapType)

		// String constructor.
		fmt.Fprintf(&b, "// New%s creates a %s from a %s string.\n", t.Name, t.Name, mat)
		fmt.Fprintf(&b, "func New%s(%s string) (*%s, error) {\n", t.Name, mat, t.Name)
		fmt.Fprintf(&b, "\t%s, err := %s(%q, %s)\n", c.field, c.newFn, t.Format, mat)
		fmt.Fprintf(&b, "\tif err != nil {\n\t\treturn nil, err\n\t}\n")
		fmt.Fprintf(&b, "\treturn &%s{%s}, nil\n}\n\n", t.Name, c.field)

		// Raw-bytes constructor (spec §4.2).
		fmt.Fprintf(&b, "// New%sFromBytes creates a %s from a raw %s byte slice.\n", t.Name, t.Name, mat)
		fmt.Fprintf(&b, "func New%sFromBytes(%s []byte) (*%s, error) {\n", t.Name, mat, t.Name)
		fmt.Fprintf(&b, "\t%s, err := %s(%q, %s)\n", c.field, c.newBytesFn, t.Format, mat)
		fmt.Fprintf(&b, "\tif err != nil {\n\t\treturn nil, err\n\t}\n")
		fmt.Fprintf(&b, "\treturn &%s{%s}, nil\n}\n\n", t.Name, c.field)

		// Keyless constructor (testing only).
		fmt.Fprintf(&b, "// New%sKeyless creates a %s with the hardcoded %s (testing only — NOT SECURE).\n", t.Name, t.Name, mat)
		fmt.Fprintf(&b, "func New%sKeyless() (*%s, error) {\n", t.Name, t.Name)
		fmt.Fprintf(&b, "\t%s, err := %s(%q)\n", c.field, c.keylessFn, t.Format)
		fmt.Fprintf(&b, "\tif err != nil {\n\t\treturn nil, err\n\t}\n")
		fmt.Fprintf(&b, "\treturn &%s{%s}, nil\n}\n\n", t.Name, c.field)

		// Forwarding methods (the Codec surface).
		fmt.Fprintf(&b, "// Enc encrypts and encodes plaintext to obtext.\n")
		fmt.Fprintf(&b, "func (c *%s) Enc(plaintext string) (string, error) { return c.%s.Enc(plaintext) }\n\n", t.Name, c.field)
		fmt.Fprintf(&b, "// Dec decodes and decrypts obtext to plaintext.\n")
		fmt.Fprintf(&b, "func (c *%s) Dec(obtext string) (string, error) { return c.%s.Dec(obtext) }\n\n", t.Name, c.field)
		fmt.Fprintf(&b, "// Format returns the fixed format (scheme + encoding).\n")
		fmt.Fprintf(&b, "func (c *%s) Format() %sFormat { return c.%s.Format() }\n\n", t.Name, c.qual, c.field)
		fmt.Fprintf(&b, "// Scheme returns the fixed scheme.\n")
		fmt.Fprintf(&b, "func (c *%s) Scheme() %sScheme { return c.%s.Scheme() }\n\n", t.Name, c.qual, c.field)
		fmt.Fprintf(&b, "// Encoding returns the fixed encoding.\n")
		fmt.Fprintf(&b, "func (c *%s) Encoding() %sEncoding { return c.%s.Encoding() }\n\n", t.Name, c.qual, c.field)

		// Compile-time Codec assertion.
		fmt.Fprintf(&b, "var _ %sCodec = (*%s)(nil)\n\n", c.qual, t.Name)
	}

	return b.String()
}

func writeFormatted(path, src string) {
	formatted, err := format.Source([]byte(src))
	if err != nil {
		fmt.Fprintf(os.Stderr, "gen-codecs: gofmt %s failed: %v\n\n%s", path, err, src)
		os.Exit(1)
	}
	if err := os.WriteFile(path, formatted, 0o644); err != nil {
		fmt.Fprintf(os.Stderr, "gen-codecs: write %s failed: %v\n", path, err)
		os.Exit(1)
	}
}
