// Code generated by scripts/gen-codecs; DO NOT EDIT.

package ztier

import "oboron.org/go/oboron"

// ZrbcxC32 is the fixed-format codec for "zrbcx.c32". The encoding is part of the
// type name and never optional.
type ZrbcxC32 struct{ obz *Obz }

// NewZrbcxC32 creates a ZrbcxC32 from a secret string.
func NewZrbcxC32(secret string) (*ZrbcxC32, error) {
	obz, err := NewObz("zrbcx.c32", secret)
	if err != nil {
		return nil, err
	}
	return &ZrbcxC32{obz}, nil
}

// NewZrbcxC32FromBytes creates a ZrbcxC32 from a raw secret byte slice.
func NewZrbcxC32FromBytes(secret []byte) (*ZrbcxC32, error) {
	obz, err := NewObzFromBytes("zrbcx.c32", secret)
	if err != nil {
		return nil, err
	}
	return &ZrbcxC32{obz}, nil
}

// NewZrbcxC32Keyless creates a ZrbcxC32 with the hardcoded secret (testing only — NOT SECURE).
func NewZrbcxC32Keyless() (*ZrbcxC32, error) {
	obz, err := NewObzKeyless("zrbcx.c32")
	if err != nil {
		return nil, err
	}
	return &ZrbcxC32{obz}, nil
}

// Enc encrypts and encodes plaintext to obtext.
func (c *ZrbcxC32) Enc(plaintext string) (string, error) { return c.obz.Enc(plaintext) }

// Dec decodes and decrypts obtext to plaintext.
func (c *ZrbcxC32) Dec(obtext string) (string, error) { return c.obz.Dec(obtext) }

// Format returns the fixed format (scheme + encoding).
func (c *ZrbcxC32) Format() oboron.Format { return c.obz.Format() }

// Scheme returns the fixed scheme.
func (c *ZrbcxC32) Scheme() oboron.Scheme { return c.obz.Scheme() }

// Encoding returns the fixed encoding.
func (c *ZrbcxC32) Encoding() oboron.Encoding { return c.obz.Encoding() }

var _ oboron.Codec = (*ZrbcxC32)(nil)

// ZrbcxB32 is the fixed-format codec for "zrbcx.b32". The encoding is part of the
// type name and never optional.
type ZrbcxB32 struct{ obz *Obz }

// NewZrbcxB32 creates a ZrbcxB32 from a secret string.
func NewZrbcxB32(secret string) (*ZrbcxB32, error) {
	obz, err := NewObz("zrbcx.b32", secret)
	if err != nil {
		return nil, err
	}
	return &ZrbcxB32{obz}, nil
}

// NewZrbcxB32FromBytes creates a ZrbcxB32 from a raw secret byte slice.
func NewZrbcxB32FromBytes(secret []byte) (*ZrbcxB32, error) {
	obz, err := NewObzFromBytes("zrbcx.b32", secret)
	if err != nil {
		return nil, err
	}
	return &ZrbcxB32{obz}, nil
}

// NewZrbcxB32Keyless creates a ZrbcxB32 with the hardcoded secret (testing only — NOT SECURE).
func NewZrbcxB32Keyless() (*ZrbcxB32, error) {
	obz, err := NewObzKeyless("zrbcx.b32")
	if err != nil {
		return nil, err
	}
	return &ZrbcxB32{obz}, nil
}

// Enc encrypts and encodes plaintext to obtext.
func (c *ZrbcxB32) Enc(plaintext string) (string, error) { return c.obz.Enc(plaintext) }

// Dec decodes and decrypts obtext to plaintext.
func (c *ZrbcxB32) Dec(obtext string) (string, error) { return c.obz.Dec(obtext) }

// Format returns the fixed format (scheme + encoding).
func (c *ZrbcxB32) Format() oboron.Format { return c.obz.Format() }

// Scheme returns the fixed scheme.
func (c *ZrbcxB32) Scheme() oboron.Scheme { return c.obz.Scheme() }

// Encoding returns the fixed encoding.
func (c *ZrbcxB32) Encoding() oboron.Encoding { return c.obz.Encoding() }

var _ oboron.Codec = (*ZrbcxB32)(nil)

// ZrbcxB64 is the fixed-format codec for "zrbcx.b64". The encoding is part of the
// type name and never optional.
type ZrbcxB64 struct{ obz *Obz }

// NewZrbcxB64 creates a ZrbcxB64 from a secret string.
func NewZrbcxB64(secret string) (*ZrbcxB64, error) {
	obz, err := NewObz("zrbcx.b64", secret)
	if err != nil {
		return nil, err
	}
	return &ZrbcxB64{obz}, nil
}

// NewZrbcxB64FromBytes creates a ZrbcxB64 from a raw secret byte slice.
func NewZrbcxB64FromBytes(secret []byte) (*ZrbcxB64, error) {
	obz, err := NewObzFromBytes("zrbcx.b64", secret)
	if err != nil {
		return nil, err
	}
	return &ZrbcxB64{obz}, nil
}

// NewZrbcxB64Keyless creates a ZrbcxB64 with the hardcoded secret (testing only — NOT SECURE).
func NewZrbcxB64Keyless() (*ZrbcxB64, error) {
	obz, err := NewObzKeyless("zrbcx.b64")
	if err != nil {
		return nil, err
	}
	return &ZrbcxB64{obz}, nil
}

// Enc encrypts and encodes plaintext to obtext.
func (c *ZrbcxB64) Enc(plaintext string) (string, error) { return c.obz.Enc(plaintext) }

// Dec decodes and decrypts obtext to plaintext.
func (c *ZrbcxB64) Dec(obtext string) (string, error) { return c.obz.Dec(obtext) }

// Format returns the fixed format (scheme + encoding).
func (c *ZrbcxB64) Format() oboron.Format { return c.obz.Format() }

// Scheme returns the fixed scheme.
func (c *ZrbcxB64) Scheme() oboron.Scheme { return c.obz.Scheme() }

// Encoding returns the fixed encoding.
func (c *ZrbcxB64) Encoding() oboron.Encoding { return c.obz.Encoding() }

var _ oboron.Codec = (*ZrbcxB64)(nil)

// ZrbcxHex is the fixed-format codec for "zrbcx.hex". The encoding is part of the
// type name and never optional.
type ZrbcxHex struct{ obz *Obz }

// NewZrbcxHex creates a ZrbcxHex from a secret string.
func NewZrbcxHex(secret string) (*ZrbcxHex, error) {
	obz, err := NewObz("zrbcx.hex", secret)
	if err != nil {
		return nil, err
	}
	return &ZrbcxHex{obz}, nil
}

// NewZrbcxHexFromBytes creates a ZrbcxHex from a raw secret byte slice.
func NewZrbcxHexFromBytes(secret []byte) (*ZrbcxHex, error) {
	obz, err := NewObzFromBytes("zrbcx.hex", secret)
	if err != nil {
		return nil, err
	}
	return &ZrbcxHex{obz}, nil
}

// NewZrbcxHexKeyless creates a ZrbcxHex with the hardcoded secret (testing only — NOT SECURE).
func NewZrbcxHexKeyless() (*ZrbcxHex, error) {
	obz, err := NewObzKeyless("zrbcx.hex")
	if err != nil {
		return nil, err
	}
	return &ZrbcxHex{obz}, nil
}

// Enc encrypts and encodes plaintext to obtext.
func (c *ZrbcxHex) Enc(plaintext string) (string, error) { return c.obz.Enc(plaintext) }

// Dec decodes and decrypts obtext to plaintext.
func (c *ZrbcxHex) Dec(obtext string) (string, error) { return c.obz.Dec(obtext) }

// Format returns the fixed format (scheme + encoding).
func (c *ZrbcxHex) Format() oboron.Format { return c.obz.Format() }

// Scheme returns the fixed scheme.
func (c *ZrbcxHex) Scheme() oboron.Scheme { return c.obz.Scheme() }

// Encoding returns the fixed encoding.
func (c *ZrbcxHex) Encoding() oboron.Encoding { return c.obz.Encoding() }

var _ oboron.Codec = (*ZrbcxHex)(nil)

// Legacy is the fixed-format codec for "legacy". The encoding is part of the
// type name and never optional.
type Legacy struct{ obz *Obz }

// NewLegacy creates a Legacy from a secret string.
func NewLegacy(secret string) (*Legacy, error) {
	obz, err := NewObz("legacy", secret)
	if err != nil {
		return nil, err
	}
	return &Legacy{obz}, nil
}

// NewLegacyFromBytes creates a Legacy from a raw secret byte slice.
func NewLegacyFromBytes(secret []byte) (*Legacy, error) {
	obz, err := NewObzFromBytes("legacy", secret)
	if err != nil {
		return nil, err
	}
	return &Legacy{obz}, nil
}

// NewLegacyKeyless creates a Legacy with the hardcoded secret (testing only — NOT SECURE).
func NewLegacyKeyless() (*Legacy, error) {
	obz, err := NewObzKeyless("legacy")
	if err != nil {
		return nil, err
	}
	return &Legacy{obz}, nil
}

// Enc encrypts and encodes plaintext to obtext.
func (c *Legacy) Enc(plaintext string) (string, error) { return c.obz.Enc(plaintext) }

// Dec decodes and decrypts obtext to plaintext.
func (c *Legacy) Dec(obtext string) (string, error) { return c.obz.Dec(obtext) }

// Format returns the fixed format (scheme + encoding).
func (c *Legacy) Format() oboron.Format { return c.obz.Format() }

// Scheme returns the fixed scheme.
func (c *Legacy) Scheme() oboron.Scheme { return c.obz.Scheme() }

// Encoding returns the fixed encoding.
func (c *Legacy) Encoding() oboron.Encoding { return c.obz.Encoding() }

var _ oboron.Codec = (*Legacy)(nil)
